### ISSUE TITLE
Enhance autoupdater

### ISSUE THREAD

**Issue by viktorgullmark** [viktorgullmark/exilence-next#118]
We should poll github every 10min or so and open a dialog or notify the user in some way that an update is available, with options to update now or later. 

See old exilence for logic behind this.

**Comment by petterannerwall** [comment]
See the logic we had in old exilence for polling [here](https://github.com/viktorgullmark/exilence/blob/4cc7ad25d9f22a61619d86b4161a491213d68fae/ExilenceClient/src/app/authorize/components/notfication-bar/notfication-bar.component.ts), this should probably be done in a service or something

The old interfaces are [here ](https://github.com/viktorgullmark/exilence/blob/9fe0d487b26e66ddccdf40e476342bb960afef0f/ExilenceClient/src/app/shared/interfaces/github.interface.ts)
