### ISSUE TITLE
Ability to cancel current snapshot in progress

### ISSUE THREAD

**Issue by viktorgullmark** [viktorgullmark/exilence-next#140]
This will require us to rewrite parts of the snapshot action flow, so we can cancel the observables using rxjs.

**Comment by hammypants** [comment]
Upvote w/ use case:

On new league start I no longer care about old profiles. Often times I take significant time off (the last month) of a league before the new one begins; so, I don't often manage Exilence in the interim. Upon opening, some auth portions usually fail (expected), and a bunch of stuff auto-fetches unless I have disabled it the month prior. I most often just want to cancel all of that fetching, nuke those profiles, and start over. Allowing canceling of snapshots (or other fetches) seems like the shortest path there.

**Comment by viktorgullmark** [comment]
Fixed this for the upcoming 1.0 release. Closing this issue.
