### ISSUE TITLE
Unified backend logging

### ISSUE THREAD

**Issue by petterannerwall** [viktorgullmark/exilence-next#244]
We need to add logging to most hub methods on backend and implement a logging system to file. 

We should also have logging to a password protected signalr group.

We should look into using NLog for logging to file

**Comment by jackjwilliams** [comment]
You should also consider Serilog. It has much more updated API's, less XML configuration file based and has extensible sinks (file sink, debug / console sink, Elastilog / Kibana sink, etc...).

If you'd be open to this I can put up a PR
