### ISSUE TITLE
Stacked Deck Priced at 69c

### ISSUE THREAD

**Issue by olafurw** [viktorgullmark/exilence-next#346]
**Describe the bug**
When taking a snapshot, stacked deck is priced at 69c

Neither poe.watch nor poe.ninja have stacked deck at those prices.

exilence

![image](https://user-images.githubusercontent.com/103783/72833737-b994a700-3c87-11ea-860e-c44338fda1c3.png)

ninja

![image](https://user-images.githubusercontent.com/103783/72833766-c7e2c300-3c87-11ea-904b-de1e6f600718.png)

watch

![image](https://user-images.githubusercontent.com/103783/72833810-dcbf5680-3c87-11ea-84ba-d095501c125a.png)

**Comment by viktorgullmark** [comment]
Thanks for the report. This is a known bug due to hickups at https://poe.ninja, see https://github.com/viktorgullmark/exilence-next/issues/295 for updates regarding this. 

We have a way of dodging these hickups but haven't gotten around to implementing it yet.
