### ISSUE TITLE
Show (sub) net worth based on search query

### ISSUE THREAD

**Issue by fthiesse** [viktorgullmark/exilence-next#373]
Sometimes it's interesting to see what certain items are worth. At the moment one would need to set up a new profile or atleast rearrange items to specific stashes.

One way around would be to show a "sub net worth" below the total net worth based on the active search query. For example to get an idea of what all scarabs in all selected/active stahes are worth, one would simply write "Scarab" into the search bar to filter for them and have the sum displayed below the total net worth.

**Comment by viktorgullmark** [comment]
This is a really good idea. We should really display the net worth based on the search too, not only the total value. However, I would probably want this value display to be positioned with the table, since we want to decouple widgets as much as possible.

Thanks for the request!
