### ISSUE TITLE
Persist sort/order selection

### ISSUE THREAD

**Issue by TheOne320** [viktorgullmark/exilence-next#426]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I sort by "Total" and switch to settings and back to net worth and the sorting is reset to "Name".

**Describe the solution you'd like**
I want the App to save which sort option was last selected and keep it even after a new snapshot or even after restarting the App.

**Describe alternatives you've considered**
No alternatives conceivable.

**Additional context**
![image](https://user-images.githubusercontent.com/7705568/73498042-755a8280-43bc-11ea-8b50-6ab6290d37a9.png)

**Comment by viktorgullmark** [comment]
Thanks for the request. Will implement this!
