### ISSUE TITLE
Auto snapshotting stops working for some users

### ISSUE THREAD

**Issue by viktorgullmark** [viktorgullmark/exilence-next#436]
We've had several reports of auto snapshotting that stops working for some users. 

This should be investigated.

UPDATE: Seems to be caused by prices being fetched at the same time.

**Comment by Chrimle** [comment]
I've encountered it once more, this time I spotted what caused it. So for some reason, it could fetch and valuate my stash tabs, however, the session failed to initialize.

Once it failed to initialize, it appears to "never" retry. (I've let it run for up to 2 hours, without it being initialized).

This may not help in trying to reproduce the problem, but rather give more insight of my encounter with this problem.

**Comment by viktorgullmark** [comment]
Thanks a lot for the information. What version was this on, 0.2.6 or 0.2.7?

**Comment by Chrimle** [comment]
0.2.6

**Comment by viktorgullmark** [comment]
Can you see if you can reproduce this on 0.2.7? We did some changes to the initialize session logic in the latest release.

**Comment by Chrimle** [comment]
Yeah, I read the patch notes. But I can't confirm nor deny if those changes have solved the problem, since I haven't encountered the problem with 0.2.7 (yet).

But I will comment here once more if I happen to encounter the problem with 0.2.7, for sure.

**Comment by Chrimle** [comment]
![image](https://user-images.githubusercontent.com/28791817/73849950-1fa63000-482b-11ea-808a-1d1bc7980d1a.png)
The problem persists, although, this time I don't know what caused it...

(0.2.7 with Auto-snapshot set to 5 Minutes)

**Comment by viktorgullmark** [comment]
Thanks a lot for the information. I think I know what's causing it now. It seems that the price fetching is interfering with the snapshotting sequence. 

Every time we snapshot we make sure that prices are not being fetched (as well as some other criteria), and it seems as if it just stops queuing snapshots if thats the case.

Thanks a lot again, will continue to investigate.
