### ISSUE TITLE
Intervals stop working randomly

### ISSUE THREAD

**Issue by viktorgullmark** [viktorgullmark/exilence-next#463]
I've experienced this once, which means I have no clue how to reproduce it.

However, after closing the server the following happened:
- SignalR retry interval stopped ticking
- SetTimeLabel interval stopped ticking

This lead to me not regaining a connection, since the retry interval was cancelled.

**Comment by klonamy** [comment]
I have the bug as well.
Just edited the auto interval to 15 and it stopped working.
I think i will reset it to the default 5 minutes.

Maybe it is that it writes the minutes wrong to settings file?

**Comment by klonamy** [comment]
Auto-Updates functions if it is set to 5 minutes it seems.
