### ISSUE TITLE
Ancient Shard missing

### ISSUE THREAD

**Issue by git42leech** [viktorgullmark/exilence-next#470]
Ancient Shards are missing, unlike Exalted. Seems like a bigger issue with fetching data from poe.ninja, since they don't list Ancient Shards at all.

**Comment by viktorgullmark** [comment]
Thanks for the issue! Leaving this open until poe.watch has been added.

**Comment by viktorgullmark** [comment]
Closing as poe.watch is no longer maintained. Ive raised this issue to poe.ninja, so he knows about it.
