### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by sdemi** [viktorgullmark/exilence-next#471]
**Describe the bug**
Entering Session Id and clicking AUTHORIZE doesn't log you in. Gives error - "validate session failed Request failed with status code 401"

**To Reproduce**
1. Enter Session Id
2. Click AUTHORIZE

**Expected behavior**
You are able to login.

**Screenshots**
Session ID - https://i.imgur.com/prMu589.png
App error - https://i.imgur.com/6T5nfey.png

**Version**
0.2.10

**Comment by viktorgullmark** [comment]
Thanks for the info. Have you logged in to multiple accounts on the same computer in Exilence Next?

**Comment by sdemi** [comment]
No I use only one account. But I also do have Currency Cop and Exilence (deprecated app), that I am logged in to on the same account. Do I need to uninstall Exilence?

**Comment by sdemi** [comment]
Session Id may be different in those apps however, not sure if that matters

**Comment by viktorgullmark** [comment]
This should not affect anything. Have you tried generating a new session id from the site by relogging completely there?

**Comment by sdemi** [comment]
Thanks that worked.
