### ISSUE TITLE
https://jshare.com.cn/temp/ZOGGQw  旭日图显示问题有负值情况下

### ISSUE THREAD

**Issue by weixingcai** [viktorgullmark/exilence-next#476]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by weixingcai** [comment]
https://jshare.com.cn/temp/ZOGGQw

**Comment by viktorgullmark** [comment]
Stop posting this kinds of issues. If you want attention fill in the form.
