### ISSUE TITLE
Reading map tiers

### ISSUE THREAD

**Issue by B3nSleazy** [viktorgullmark/exilence-next#477]
**Describe the bug**
software reads teir 1 maps as t14 for pricing. 

**To Reproduce**
have t1 jungle valley map
take snapshot and view price - lists white map as red map for 5 chaos

**Expected behavior**
supposed to read as proper tier 1 white map for pricing

**Screenshots**

**Version**
2.10

**Additional context**

**Comment by viktorgullmark** [comment]
This has been fixed in the latest release, closing.
