### ISSUE TITLE
Add setting to toggle hardware acceleration

### ISSUE THREAD

**Issue by StazOne** [viktorgullmark/exilence-next#486]
Hey, can you add hardware acceleration toggle option? Hardware acceleration is destroying my UI.

**Comment by viktorgullmark** [comment]
I think you can add launch options to the .exe if I'm not mistaken, to manually do this.

With that said, we'll evaluate if this is something we can implement.

**Comment by petterannerwall** [comment]
We can do it with a setting as well, see here

https://www.electronjs.org/docs/tutorial/offscreen-rendering
https://github.com/electron/electron/issues/13368

**Comment by frochi42** [comment]
Please note that I'm also fighting with this problem (using "MS teams" and "slack" in an linux ubuntu 18.04 environment). These apps are simply not usable. The solution with app.disableHardwareAcceleration() obviously only works when this code is included in the app's code. But it must be also possible to switch it at startup time (e.g. via ENV-variable of configuration file).
