### ISSUE TITLE
Persist groups on restart

### ISSUE THREAD

**Issue by S0T0** [viktorgullmark/exilence-next#487]
**Describe the bug**
All created/joined groups after restarting the application(or computer restarts) are deleted and need to be re-created and re-joined by all members manually.

**To Reproduce**
1. Make/Join a group
2. Restart application
3. All groups you joined/created are gone

**Expected behavior**
Groups should be saved and automatically rejoined.

**Screenshots**
None.

**Version**
V.0.2.11

**Additional context**
Not sure if this is a suggestion or not, this seems like it isn't intended.

**Comment by viktorgullmark** [comment]
Thanks for the input. This is something we have in mind but seems like we don't have an issue for it. Will leave this open!

**Comment by sbsrnt** [comment]
Duplicate - https://github.com/viktorgullmark/exilence-next/issues/371
