### ISSUE TITLE
Session ID for new users

### ISSUE THREAD

**Issue by dreais** [viktorgullmark/exilence-next#494]
**Is your feature request related to a problem? Please describe.**
i first started exilence next as a friend advised me to. thing is, first menu is the "session id" prompt, that i don't know of. no explanation provided on what it is, or where to find it

**Describe the solution you'd like**
leaving a link (https://github.com/Stickymaddness/Procurement/wiki/SessionID) or explaining HOW to get that ID would be useful

thanks!

**Comment by viktorgullmark** [comment]
Hi! 

Thanks for the feedback.

This actually exists already, although it might be subtle.

![image](https://user-images.githubusercontent.com/11405940/77126079-2c33c000-6a48-11ea-9b63-ea1b75fbda1d.png)
