### ISSUE TITLE
Prices are retrieved incorrectly

### ISSUE THREAD

**Issue by 3789037** [viktorgullmark/exilence-next#505]
**Describe the bug**
Several items (at least) have dramatically incorrect values. For example, poe.ninja currently values the Simulacrum at ~65c, but the client shows the value as 380c. [Here ](https://pastebin.com/qqMgR0CB) is an exported CSV

**To Reproduce**
1. Fetch Snapshot
2. Observe incorrect prices
**Expected behavior**
Prices match the prices displayed by poe.ninja

**Screenshots**
https://imgur.com/a/Disy5hW

**Version**
v0.3.1

**Comment by viktorgullmark** [comment]
@3789037 This is most likely due to an incorrect setting on your end. Make sure your profile price league setting is correct.

**Comment by 3789037** [comment]
Ah yes, you are correct. I had standard league selected. Perhaps it would be better to default the pricing league to the character league when setting up a new user?

Sorry for bothering, thanks for the quick help.

**Comment by viktorgullmark** [comment]
Might be a good idea, we'll see what we can do. No worries!
