### ISSUE TITLE
Total price treshold

### ISSUE THREAD

**Issue by domagojmedo** [viktorgullmark/exilence-next#510]
**Is your feature request related to a problem? Please describe.**

Exilence shows a lot of divination cards as 1c when they actually aren't. And even when some are it's hard to sell them. This is more problem with poe.ninja maybe but we can't fix that side.

**Describe the solution you'd like**
I would like an option like the treshold option we have that would limit the items included in networth if total stack value is less than X. Also it would be nice if it's free input instead of predefined dropdown.
So most of the essences and divination cards would be hidden but if I put a valuable essence or card in their tab it would pop up in items section in Exilence because they are worth more than X.
Or when I get enough of a card hat total value is more than X then I can move it to Shop tab and price to sell.

**Comment by viktorgullmark** [comment]
Thanks for the suggestion. An issue already exists for this, see https://github.com/viktorgullmark/exilence-next/issues/414. Closing :)
