### ISSUE TITLE
Bulk item pricing

### ISSUE THREAD

**Issue by domagojmedo** [viktorgullmark/exilence-next#522]
**Is your feature request related to a problem? Please describe.**
In app it shows how much is each currency worth in chaos. But it doesn't show how many of the currency you have to trade for 1 chaos.

**Describe the solution you'd like**
It would be nice if we would have an option to get bulk pricing for chaos. For example if jeweller orbs are worth 0.08c each then it would show 1/12 or (1/12.5) and we could just take that and put it as bulk price.
Maybe even add slider or something for minimum trade amount. Lets say we have 500 jeweller orbs but want to trade minimum 100 orbs in a single trade then it would generate 8/100. Or maybe just offer multiples of 12 in this case.

**Comment by viktorgullmark** [comment]
This is not something we will implement since all the ratios are readily visible in other resources such as poe.trade
