### ISSUE TITLE
Worked when I got it and now it doesn't

### ISSUE THREAD

**Issue by DirtyDeej** [viktorgullmark/exilence-next#529]
I downloaded Exilence Next latest release 2 weeks ago and it worked just fine. I went to use it today and it no longer works. When I opened it the program was running but the window was blank/transparent. There was a border for the window of which I could see exilence next in the top left and I could click maximize or close in the top right although I could not see the icons for them. I could also drag the window and when I did the visual appearance of the borders would become distorted. I've tried reinstalling and using previous versions but the result was the same. I tried downloading old Exilence and that one did work.  Not sure if it has anything to do with it but I'm using windows 7. Any help or insight into this issue would be greatly appreciated. Thanks

**Comment by viktorgullmark** [comment]
Can you attach some printscreens of the issue? Would help! Also, this might have something to do with you running Windows 7. We don't have the ability to test it on Win 7 and won't build support for it if it doesn't work out of the box.

**Comment by DirtyDeej** [comment]
Here are some images of the appearance after downloading a fresh copy just now. 

![exi1](https://user-images.githubusercontent.com/63481073/79054438-da2f2600-7c12-11ea-8ae9-76179dab3673.png)
![exi2](https://user-images.githubusercontent.com/63481073/79054511-5a558b80-7c13-11ea-9c44-8fb6a61c2a4e.png)

**Comment by viktorgullmark** [comment]
I'm afraid I can't help as I haven't seen this before. I would suggest swapping to Windows 10, other than that I can not help you.
