### ISSUE TITLE
Can't authorize. Error 403

### ISSUE THREAD

**Issue by Silentguard** [viktorgullmark/exilence-next#531]
Got disconnected when taking snapshot. After that getting 403 response. Tried to reloged several times to get new session ID and update program.

**Expected behavior**
Supposed to log in

**Screenshots**
![image](https://user-images.githubusercontent.com/13031465/79057686-90881f00-7c96-11ea-875e-cf62cea24bf1.png)

**Version**
0.3.5 and 0.3.6

**Additional context**
Changed settings of autosnapshot to 10 minutes. Filter\search string = 4.

**Comment by Azriael2** [comment]
Same problem here, I guess GGG changed something on their side?

**Comment by justin-capalbo** [comment]
Same here.  I read somewhere that they have a list of whitelisted apps?  Not sure exactly though

**Comment by kinzozs** [comment]
Same problem here, hope it can get fixed soon :)

**Comment by AbeLincoln** [comment]
I can also reproduce this with v.0.3.6.

**Comment by Silentguard** [comment]
Also
![image](https://user-images.githubusercontent.com/13031465/79058101-d7c4de80-7c9b-11ea-8744-c444251ddce7.png)

**Comment by eliebeaino** [comment]
same issue here, just noticed my app is no longer, i tried re-entering the session ID but still same.

**Comment by ibaragin-x** [comment]
same issue. 
re-issuing a  session-ID doesnt work either, seems to be on GGGs end.

**Comment by storxusmc** [comment]
same on all programs that use session id

**Comment by jorupp** [comment]
I think it's something with cloudflare and the user agent.  If I intercept the ExilenceNext call with Fiddler and change it to use my browser's user agent, it goes through.  Otherwise, I get what appears to be an error from Cloudflare - probably that same DDoS protection that shows that "checking your browser" message before attempting to access `/login`.

**Comment by mayplex** [comment]
same problem here

**Comment by DarkDynamix** [comment]
same issue.
changing session-ID doesnt work either.

**Comment by acidreian666** [comment]
+1 to this issue hopefully fixed soon :(

**Comment by hammypants** [comment]
> I think it's something with cloudflare and the user agent. If I intercept the ExilenceNext call with Fiddler and change it to use my browser's user agent, it goes through. Otherwise, I get what appears to be an error from Cloudflare - probably that same DDoS protection that shows that "checking your browser" message before attempting to access `/login`.

I changed Exilence locally to spoof the user agent and confirmed it works fine that way. Good catch.

**Comment by ELJayGee** [comment]
Same issue. Cleared cookies, deleted session id and re logged in no luck.

**Comment by acidreian666** [comment]
> > I think it's something with cloudflare and the user agent. If I intercept the ExilenceNext call with Fiddler and change it to use my browser's user agent, it goes through. Otherwise, I get what appears to be an error from Cloudflare - probably that same DDoS protection that shows that "checking your browser" message before attempting to access `/login`.
> 
> I changed Exilence locally to spoof the user agent and confirmed it works fine that way. Good catch.

Please explain i used Fiddler very few times how do you spoof the user agent?

**Comment by Xebtria** [comment]
Same issue here, I thought I am going crazy tried the session ID with 3 different browsers.... ^.^

**Comment by stvndall** [comment]
Has there been anything like this before to get an idea of how long it might be to fix on their side? 
Also do we know if GGG knows?

**Comment by acidreian666** [comment]
> Has there been anything like this before to get an idea of how long it might be to fix on their side?
> Also do we know if GGG knows?

I was just thinking the same thing 100k people using this with 2 min intervals is same thing as DDOS except on a slower scale.

**Comment by z0w13** [comment]
GGG has confirmed some 3rd party apps have been blocked due to their high API usage, not sure if they confirmed Exilence is part of that as well though.

**Comment by acidreian666** [comment]
> GGG has confirmed some 3rd party apps have been blocked due to their high API usage, not sure if they confirmed Exilence is part of that as well though.

is this news today or what?

**Comment by z0w13** [comment]
I think it's safe to assume Exilence was part of it considering they're blocking the user agent.

> Is this news today or what

https://www.reddit.com/r/pathofexile/comments/fzosgc/did_ggg_change_something_about_sessionid_and_its/fn5jasx/

> From tix#1111 on Discord:
> > I'm currently blocking requests from some tools. The website is under extremely high load and one of them accounted for 22% of non trade requests hitting the website. I'll look into which ones can be unblocked once everything is stable.

**Comment by Xebtria** [comment]
... If they would only allow reading such information from the gameclient directly instead of their weird implementation that requires everything to be read from the API because the API, the gameclient and the homepage are so intertwined it hurts.

**Comment by stark2727** [comment]
Something broke with V0.3.6

**Comment by viktorgullmark** [comment]
This is on GGG's end. We have direct contact with them about the issue. They will keep it blocked until tomorrow morning (at least) while they try to optimize their own API. Their API is under heavy load and needs to be tweaked to support this many requests.  

Follow releases-and-news channel in Discord for updates: https://discord.gg/jxnPmux

**Comment by acidreian666** [comment]
> This is on GGG's end. We have direct contact with them about the issue. They will keep it blocked until tomorrow morning (at least) while they try to optimize their own API. Their API is under heavy load and needs to be tweaked to support this many requests.
> 
> Follow releases-and-news channel in Discord for updates: https://discord.gg/jxnPmux

Thank god idk what id do without this program now days!
