### ISSUE TITLE
Exilence and Exilence next is down.

### ISSUE THREAD

**Issue by SadBananas** [viktorgullmark/exilence-next#532]
**Describe the bug**
Unable to fetch new snapshot.
**To Reproduce**
Fetch new snapshot

**Expected behavior**
Fetch new data from PoE api.

**Screenshots**
Error
![image](https://user-images.githubusercontent.com/20612376/79437087-9d27b280-7fc9-11ea-8b06-7ab09328efb2.png)

**Version**
0.3.6

**Additional context**
Every PoE player I know has this problem

**Comment by markusradtke** [comment]
It works for me. 3-4 days ago GGG limited the access for 3rd party tools. But right now everything should work fine.

**Comment by viktorgullmark** [comment]
This is related to you removing a character, stash tab, or poe.ninja having issues. Please verify and comment back.

**Comment by SadBananas** [comment]
> This is related to you removing a character, stash tab, or poe.ninja having issues. Please verify and comment back.

I have bought additional stash tabs, I did not remove any characters or stash tabs.
I have deleted all exilence data (both versions) and entered new  poe session ID. And the same thing occurs in Exilence next. In old version I get stuck on id verification.
