### ISSUE TITLE
incubator prices way off

### ISSUE THREAD

**Issue by waenc** [viktorgullmark/exilence-next#535]
On 22.04.2020 Incubators are being given a price higher than on poe.ninja. For example, Mysterious Incubator is 10c in app but 1c on poe.ninja.

**Screenshots**
[exilence next](https://i.imgur.com/dMfPMUi.png)
[poe.ninja](https://i.imgur.com/OIHxWzS.png)

**Version**
0.3.6

**Comment by viktorgullmark** [comment]
See our #FAQ channel in the Discord.
