### ISSUE TITLE
Map tier is not accounted for when pricing

### ISSUE THREAD

**Issue by jwfiredragon** [viktorgullmark/exilence-next#536]
E.g. put a T4 Courtyard and a T8 Courtyard in the same tab and get a snapshot. Exlience will only list a single line for two T8 Courtyard maps, at 1c each, instead of one T4 Courtyard at 0.8c and one T8 Courtyard at 1c.

EDIT: After some testing, it appears the issue is actually that all maps are priced at the highest tier of map in the tab. E.g. if you put a bunch of Courtyards in a tab, with the highest being T8, they'd all be priced as T8 Courtyards.

**Comment by Wibbbs** [comment]
I also feel like something is going on here. Not sure what tho.

![image](https://user-images.githubusercontent.com/24574428/89341537-76bc7e80-d66f-11ea-8014-8540aed6a3cc.png)

**Comment by viktorgullmark** [comment]
Should be solved with the latest release
