### ISSUE TITLE
Price change (snapshot comparison)

### ISSUE THREAD

**Issue by mafima** [viktorgullmark/exilence-next#537]
**Is your feature request related to a problem? Please describe.**
Seeing what price changed the most in comparison from the current snapshot (today) to the last snapshot (for example3 days ago). 
Problem: I want to quickly identify which item got more valuable, like in poe ninja.

**Describe the solution you'd like**
click on the last snapshot to see the prices on that snapshot.

**Describe alternatives you've considered**
See a "price change" row unter "items". for example: 

| Name | ... | Price | price change (compared to last snapshot) | total value |
| ------------- | -------------  | -------------  | ------------- | ------------- |
|Exalted orbs | ... | 100 | +25% | 400 |

**Additional context**
this would require the price data of ALL items from the LAST snapshot. i dont know if the pricedata is discarded for all snapshots other than the current.

![image](https://user-images.githubusercontent.com/3407209/80614123-5e204500-8a3e-11ea-9571-056baee0e73f.png)

**Comment by viktorgullmark** [comment]
Thanks for the feedback. We have this in mind, but in a simpler way to start off with:

https://github.com/viktorgullmark/exilence-next/issues/496

Right now we dont store the items for all previous snapshots as this would cause memory leaks on the clients end.
