### ISSUE TITLE
Session ID Help dead link

### ISSUE THREAD

**Issue by Gottschkopf** [viktorgullmark/exilence-next#540]
The link to the help about "Help finding the Session ID" on the login is dead and the Readme doesn't explain anything about setting the program up.

**Comment by Gottschkopf** [comment]
![Help](https://user-images.githubusercontent.com/24585791/84190658-95e7c700-aa97-11ea-87a7-6d165cc41ed5.jpg)

**Comment by petterannerwall** [comment]
This was fixed before harvest league release. We wrote our own instructions and linked to all major browsers documentation on how to inspect cookies.
