### ISSUE TITLE
Seeds and new flowers are not getting price checked

### ISSUE THREAD

**Issue by MorkaZ** [viktorgullmark/exilence-next#557]
Seeds and new flowers are not getting price checked

**Comment by viktorgullmark** [comment]
This requires more work. We need to add a property for `levelRequired` and separate it into two categories as poe.ninja does, see https://poe.ninja/challenge/seeds (one for 1-75, one for 76+).

The item type seems to be classified as a currency item, so the pricing needs to be done for itemType 5.
