### ISSUE TITLE
Cannot install 0.3.9 from installer.exe on windows 10

### ISSUE THREAD

**Issue by rohitkumar93** [viktorgullmark/exilence-next#564]
**Describe the bug**
Cannot install exilence-next. Installer stuck at ~35% since yesterday. Tried restarting the installer, tried an older version(3.6), the PC, removing the installer process from task manager, deleted folder from roaming folder.

**To Reproduce**
1. Go to 'https://github.com/viktorgullmark/exilence-next/releases/tag/v0.3.9' and download the Exilence-Next-Setup-0.3.9.exe

2. Run it, to watch it stay at ~35% forever. Been atleast 36 hours with 0 change. when installer is started, it goes to 35% and then never moves at all
3. ????

**Expected behavior**
Should install like it did when exilence next was exilence

**Screenshots**
![image](https://user-images.githubusercontent.com/16209182/90221457-da8d3700-de27-11ea-8ccc-97282e539262.png)

**Version**
https://github.com/viktorgullmark/exilence-next/releases/tag/v0.3.9

**Additional context**
Windows 10,
![image](https://user-images.githubusercontent.com/16209182/90221541-fdb7e680-de27-11ea-859f-e0b92d9d736a.png)

**Comment by itsdaburgundy** [comment]
I have this too..

**Comment by viktorgullmark** [comment]
Issue tracked here: https://github.com/electron-userland/electron-builder/issues/4057#issuecomment-707229837

Will be solved when we update this package, since it was recently merged. Will create a issue for updating.
