### ISSUE TITLE
Snapshots not working.

### ISSUE THREAD

**Issue by Zerodeck** [viktorgullmark/exilence-next#567]
Just started the new Heist league, and set up a new profile on Exilence Next - It keeps saying failed to snapshot though for some reason, I can't get any updates on my stash tabs

![image](https://user-images.githubusercontent.com/24996534/93654338-c19d1600-f9d1-11ea-9080-5f568a8a4156.png)

**Comment by Razunter** [comment]
Yep, it also tries to get tabs from previous leagues for some reason.

**Comment by chupasaurus** [comment]
Fixed by author with 0.3.10

**Comment by Armeos** [comment]
I'm having the same issue, even after updating to 0.3.10

![image](https://user-images.githubusercontent.com/62191336/94484603-b0f75780-01aa-11eb-895f-fa6f05559529.png)

![image](https://user-images.githubusercontent.com/62191336/94484629-b9e82900-01aa-11eb-9e6e-012e1de8653d.png)

**Comment by razorbladehnt** [comment]
Make sure you select correct character name
mine was deleted and i had this issue
