### ISSUE TITLE
White screen on startup

### ISSUE THREAD

**Issue by NGeertinger** [viktorgullmark/exilence-next#571]
**Describe the bug**
When starting the program a white screen shows and it is stuck there. Reinstalling does not help, installing earlier versions does not help either. Exilence Next has been working just fine for me until today.

**To Reproduce**
Open the program.

**Expected behavior**
Normal behaviour.

**Screenshots**
![image](https://user-images.githubusercontent.com/29235269/95025280-d7286600-0688-11eb-9308-9a2b0851fd05.png)

**Version**
The issue persists for me after uninstalling and reinstalling the following versions:
0.3.10
0.3.9
0.2.10

**Additional context**

**Comment by 4in4eput** [comment]
Same here. I also tried reinstalling and restarting my PC. Didn't help. I'm on Windows 10.

**Comment by Maciekiwa** [comment]
okey so, i have same issue. today i finally find well easy way to fix this.
First delete exilence, then go to windows type %appdata% and there delete exilence folder, and now reinstall exilence

**Comment by 4in4eput** [comment]
^Thanks for the solution above.

I don't think it a problem with overlay though, because I've never used overlay myself and still got this issue.

**Comment by viktorgullmark** [comment]
Thanks for the information guys, will keep a look out for this.
