### ISSUE TITLE
Custom Installation

### ISSUE THREAD

**Issue by Sinacam** [viktorgullmark/exilence-next#572]
**Is your feature request related to a problem? Please describe.**
Don't install to a fixed path, let the user decide. This is a big no-go for me, as I'm sure for many others.

**Describe the solution you'd like**
Have a default path, but allow for custom installation path. Also, don't put a shortcut on the desktop automatically, that should also be user decided.

**Describe alternatives you've considered**
None.

**Additional context**
I've relocated the entire folder and it still runs, you don't have a problem with paths.

**Comment by viktorgullmark** [comment]
We will not support this since we use a prebuilt package for installing, it does not support custom paths since we use an auto updater.
