### ISSUE TITLE
Low value cards are being calculated incorectly

### ISSUE THREAD

**Issue by MorkaZ** [viktorgullmark/exilence-next#573]
Cards like "The Scholar" or "Rain of chaos" have value 1c when their real value is way lower. There are tons of cards, shards and other items that have same problem and making profit statistic way too hight than it is in reality.

**Comment by tomiesz** [comment]
have you checked the poe.ninja values for those things? The scholar shows as 1c there. 
Doesn't seem like it's an issue with exilence unless you can show a mismatch between poe.ninja and exilence. 
A simple workaround is to set it to not count stuff below ex. 2c

**Comment by MorkaZ** [comment]
> have you checked the poe.ninja values for those things? The scholar shows as 1c there.
> Doesn't seem like it's an issue with exilence unless you can show a mismatch between poe.ninja and exilence.
> A simple workaround is to set it to not count stuff below ex. 2c

It makes not real sense then to use exilence if 30% of items (or more) will be badly valued. It needs investigation.

**Comment by viktorgullmark** [comment]
It doesnt need investigation. As we have repeated multiple times we dont do ANY pricing ourselves. If it needs investigation it is on poe.ninjas end, not Exilence. We will most likely never price anything ourselves since thats a project on its own. Closing this.
