### ISSUE TITLE
Only 1 gem showing on snapshst

### ISSUE THREAD

**Issue by reeson46** [viktorgullmark/exilence-next#574]
When I take a snapshot of my gem tab (normal and Vaal), only one shows up. I'm running version 0.3.10.

[My tab](https://imgur.com/a/HyhUa4y)

[Exilence NEXT snapshot](https://imgur.com/a/0YzDWPH)

**Comment by viktorgullmark** [comment]
Compare your tab to poe.ninja and consider if they should have a price or not. Reopen this issue if theres a mismatch of Exilence and poe.ninja.
