### ISSUE TITLE
Store poe.ninja price categories in database

### ISSUE THREAD

**Issue by petterannerwall** [viktorgullmark/exilence-next#58]
Store poe.ninja price categories in database for easier update on new leagues

**Current Categories**
- Incubator
- Fossil
- Resonator
- Essence
- DivinationCard
- Prophecy
- SkillGem
- BaseType
- HelmetEnchant
- UniqueMap
- Map
- UniqueJewel
- UniqueFlaskUniqueWeapon
- UniqueArmour
- UniqueAccessory
- Beast

**Comment by viktorgullmark** [comment]
Obsolete, this will be client based
