### ISSUE TITLE
Minimize to Tray

### ISSUE THREAD

**Issue by hellridergit** [viktorgullmark/exilence-next#580]
Hello.

The application adds to the clutter on the task bar and does not offer a remedy.

I would like to be able to minimize the application to tray, just like I already can do **every** PoE-related application so far.

I attempted to use RBTray to minimize the application to tray, but it would not work on the non-standard window control buttons (RBTray's limitation).

An option to minimize the application to tray could nicely fit under the Settings > Interface.

Great stuff so far,
thanks,
H.

**Comment by viktorgullmark** [comment]
Great idea, thanks for the input. We will consider implementing this!

**Comment by sbsrnt** [comment]
Mentioned in Discord already, but will do here as well in case if someone will want to start working on that.

I have almost a complete implementation of first Tray iteration. Basically getting the initial Net Worth data is needed for Overlay and it should be ready for code review.

**Comment by viktorgullmark** [comment]
Closing, has been implemented and will be published with the next release, thanks @sbsrnt for the contribution!
