### ISSUE TITLE
Price threshold units are NaN

### ISSUE THREAD

**Issue by hellridergit** [viktorgullmark/exilence-next#585]
**Describe the bug**
Visual description: https://i.imgur.com/aShg7r8.png

**To Reproduce**
1. Install 0.3.11
2. Start Exilence Next
3. The price threshold units are now NaN

I assumed cache error and did the following:
1. Closed Exilence Next completely.
2. Removed everything under `\Users\****\AppData\Roaming\exilence-next-app\`
3. Started Exilence Next. It asked for the POESESSID again and the NaN units remained.

**Version**
0.3.11

**Comment by viktorgullmark** [comment]
Merged and will be published with the next release!
