### ISSUE TITLE
Tray->Quit does not always work

### ISSUE THREAD

**Issue by hellridergit** [viktorgullmark/exilence-next#586]
**Describe the bug**

When the Exilence Next window **is visible**
	Right click tray -> Quit (_does not close_)
	Need to use the window's close button (X) to actually close it.

When the Exilence Next **is minimized to tray**
	Right click tray -> Quit (_does not close_)
	Need to bring the window back and use its close button (X) to actually close it

**To Reproduce**

1. Install 0.3.11
2. Start Exilence Next
3. See the error

**Expected behavior**
The app is expected to be closable when the user selects `Quit`, as in with a single action.

**Version**
 0.3.11
Windows 7 SP1 x64 Ultimate

**Comment by viktorgullmark** [comment]
Thanks we will take a look at this!
