### ISSUE TITLE
Blank / white screen on app launch

### ISSUE THREAD

**Issue by sbsrnt** [viktorgullmark/exilence-next#591]
This is an ongoing issue that is hard to reproduce on our end and we keep an eye on it.

Edit: 24/04/2021
See https://github.com/viktorgullmark/exilence-next/issues/591#issuecomment-826114180

Edit: 01/03/2021
Another potential fix for newer versions:
1.  Press `ctrl + shift + i` to open the developer tools. 
2. Go to the `Application` tab at the top of the window. 
3. Navigate to `Clear Storage` in the left navigation menu
4. Press the `Clear site data` button 
5. Restart Exilence next by pressing `ctrl + r` or exit as you normally would and restart. Make sure Exilence is not running in the system tray.
6. React to this post if this solved your problem.
![image](https://user-images.githubusercontent.com/19862545/109506800-59814e80-7a9e-11eb-924d-9803bcd0d4a7.png)

---
If you have any issues related to this or have any questions and possible hints where the issue may be at feel free to reach out to us on Exilence's Discord: https://discord.gg/yxuBrPY

**Comment by Potenzo** [comment]
Having followed those steps, I am still getting a blank screen (white fullscreen) on startup with version 0.4.2.
Perhaps there's something left in the registry that wasn't cleaned up when I uninstalled 0.3.12?

**Comment by Uoipka** [comment]
My app white screened too and uninstall reinstall doesn't work

**Comment by sublimemm** [comment]
same for me. white screen. reinstall does not work.

**Comment by Omga4000** [comment]
Can confirm - still happens with version 0.4.2.
I've completely cleaned the registry & leftovers using Revo Uninstaller, and yet the white screen issue persists.
Unable to open the program, white screen on startup.

**Comment by iamtalisman** [comment]
I was having the same problem. Uninstalling the application, deleting the exilence-next-app %appdata% folder, then using **run as administrator** to reinstall the app worked for me.

**Comment by Omga4000** [comment]
> I was having the same problem. Uninstalling the application, deleting the exilence-next-app %appdata% folder, then using **run as administrator** to reinstall the app worked for me.

Can confirm that deleting the %appdata% worked.
No need to run the installer as an administrator, though.

Thanks!

**Comment by FabrizioMG** [comment]
> I was having the same problem. Uninstalling the application, deleting the exilence-next-app %appdata% folder, then using **run as administrator** to reinstall the app worked for me.

Worked for me aswell.

Thank you.

**Comment by ikelso** [comment]
This does not work for me.  

There is no exilence-next-app folder.  There is an exilence-next-app-updater folder.  I have tried uninstalling and removing that folder but it does not fix the issue.

**Comment by arturluizbr** [comment]
I'm also getting the whitescreen, tried everything listed in here and nothing seems to have any effect.

I think its safe to remove the resolved label.

**Comment by viktorgullmark** [comment]
If anyone is still experiencing this on 0.4.3 and later, let us know in this comment. We have done some reworks to how this works and should now be resolved for the most part.

**Comment by sbsrnt** [comment]
What caught our attention (and we successfully reproduced the issue) is PC name. 
Please make sure it doesn't contain any special characters like `#` or ` ` (space). 

So another potential solution is to rename your pc excluding the special characters. 

We have something in works to handle that case but until then that's all we have for now.

**Comment by sbsrnt** [comment]
Tagging for visibility:
@Potenzo  @Uoipka  @sublimemm  @ikelso  @arturluizbr 

Can you guys download latest version and see if you still have the blank screen?

**Comment by Potenzo** [comment]
Now fixed for me. Thank you for your great work!

**Comment by nikotesla01** [comment]
Bug is still happening in 5.0 and I cant find the appdata folder to uninstall

**Comment by ikelso** [comment]
Yes, still opens to a blank/white screen for me.  

On install I saw a new error:
![image](https://user-images.githubusercontent.com/18192357/127933437-4fc906d8-d228-4de0-bca2-12d0e4e9e774.png)

**Comment by AkumaNoTsubasa** [comment]
Impossible to login.
Either getting 401 or 400
Deleting Cookies, relogin, deleting exilence data, starting as admin, all you can do but nothing works.
I want the session ID login back
