### ISSUE TITLE
failed creating snapshot

### ISSUE THREAD

**Issue by bezrq** [viktorgullmark/exilence-next#592]
https://i.imgur.com/vzzpEOP.png

getting this constantly no way to fix sometimes it goes through but ussually fails happens after new update .3.14

**Comment by viktorgullmark** [comment]
Thanks for the info, have you tried restarting the app?

**Comment by viktorgullmark** [comment]
Closing, reopen this if it persists after restarting the application. I checked our server logs and cant find anything related to this.

**Comment by viktorgullmark** [comment]
Track this issue here: https://github.com/viktorgullmark/exilence-next/issues/450

**Comment by bezrq** [comment]
> Track this issue here: #450

i made a reply to #450 
its still happening for me
