### ISSUE TITLE
Add a tab where you can see all the recent items that affected net worth.

### ISSUE THREAD

**Issue by kilpsz** [viktorgullmark/exilence-next#618]
**Is your feature request related to a problem? Please describe.**
It's kind of annoying knowing that your income went up/down but have no clue which item/s contributed to it.

**Describe the solution you'd like**
A separate tab/chart where you can see all the recent items that affected net worth between x snapshots.
1.Chart which shows x most recent snapshots
2. History where you can check each snapshot or group snapshots separately

**Comment by viktorgullmark** [comment]
A first version of this has been added in PR: #755 

![image](https://user-images.githubusercontent.com/11405940/136666104-9adfc4b7-0613-44f9-bd00-5dbc7803c555.png)
