### ISSUE TITLE
clicking on view on poe.ninja for divination cards hits the wrong url

### ISSUE THREAD

**Issue by Noctis-** [viktorgullmark/exilence-next#619]
**Describe the bug**
When clicking on the view on poe.ninja for a divination card (lets use `Rebirth`) , the url that is opened is the following: 

`https://poe.ninja/challenge/divination-cards/rebirth-divcard`

which isn't correct, so it shows you the builds page.

the correct url if you go through poe.ninja is : 

`https://poe.ninja/challenge/divinationcards?name=rebirth`

**To Reproduce**
1. Open a stash that has a div card
2. Click on View on Poe.ninja
3. See wrong page 

**Expected behavior**
The relevant divination page on poe.ninja is shown

**Screenshots**

**Version**
0.4.2

**Comment by sbsrnt** [comment]
It works correctly now. `poe.ninja` changed the way they redirect divination cards.

**Comment by petterannerwall** [comment]
Closing issue by recommendation from @sbsrnt
