### ISSUE TITLE
Exilence Next does not find item thats in stash.

### ISSUE THREAD

**Issue by KristofMikle** [viktorgullmark/exilence-next#620]
**Describe the bug**
I have Fractured Tier 10 Precinct Maps in my stash in standard. I also have Fractured Tier 5 Port Map in the same stash tab. These maps are not from the current map series(Variant). When I create a snapshot it finds the Port maps, but not the Precinct maps. For the Port Map it uses the price of the Heist Variant Port Map even tho what I have in my stash is not Heist Variant.

**To Reproduce**
1. Have Tier 5 Port and Tier 10 Precinct in your stash that is tracked in the current profile. 
2. Click on Fetch Snapshot button.

**Current behavior**
Port maps Appear with price not matching the correct Map series(Variant).
Precinct maps do no appear.

**Expected behavior**
Port maps appear with price matching the correct map series(Variant).
Precinct maps appear with price matching the correct map series(Variant)

**Screenshots**

1. Port Map Heist Variant set to custom price. 
![Screenshot_4](https://user-images.githubusercontent.com/35921866/103441579-46ddcb00-4c4f-11eb-8926-9ef8b3a58c88.jpg)

2. Port Map is Priced by Heist Variant price even tho it's not that Variant.
![Screenshot_2](https://user-images.githubusercontent.com/35921866/103441567-37f71880-4c4f-11eb-95fe-a66c00ba975a.jpg)

3. Precinct Map not found.
![Screenshot_3](https://user-images.githubusercontent.com/35921866/103441583-4ba27f00-4c4f-11eb-89c7-5f6195d930c0.jpg)

4. Stash Tab with Precinct and Port maps.
![Screenshot_6](https://user-images.githubusercontent.com/35921866/103441584-4f360600-4c4f-11eb-9f80-64ad85601a2a.jpg)

5. Proof that Maps are not Heist Variant.
(If you sell to a vendor a map from old map series(Variant) then it will give you a Heist Variant Map from the same tier.
This happens on the picture, therefore we know it's not Heist Variant.)
![Screenshot_7](https://user-images.githubusercontent.com/35921866/103441586-51986000-4c4f-11eb-8c7d-98a34f6dcb86.jpg)

**Version**
v.0.4.2

**Comment by sbsrnt** [comment]
Maps are not supported by official GGG API. Neither unique tabs.

**Comment by petterannerwall** [comment]
Closing issue by recommendation from @sbsrnt
