### ISSUE TITLE
Maps are priced wrong due to targeting the wrong league

### ISSUE THREAD

**Issue by lOmicronl** [viktorgullmark/exilence-next#621]
**Describe the bug**
The app looks up prices for the wrong league variant maps on poe.ninja while the pricing league in the app is configured for Standard. This results in wrong prices, where white tier2 maps can fetch 15 chaos and more.

**To Reproduce**
1. Set Exilence Next to Standard league pricing
2. Have a map in your inventory or stash, which Exilence Next has indexed
3. Find the map in the app, and click on the "view on poe.ninja" button
4. Observe that the pricing curve is completely out of whack with Standard league trade offers on pathofexile.com
5. Note how the URL of the website ends in "harvest". For example, looking up the starter Coral Ruins map forwards to https://poe.ninja/standard/maps/coral-ruins-map-t2-harvest

**Expected behavior**
The app should fetch values for the most recent variant.

**Version**
0.4.2 (November 2nd, 2020)

**Comment by lOmicronl** [comment]
On closer examination, something even weirder is going on. I have updated the original post to more closely reflect what I am seeing.

Upon checking all of my maps, the majority of them actually point towards the correct variant ("heist"). However, a couple deviate.

The following maps are priced as Harvest variant maps in Exilence Next:

- Coral Ruins Tier 2
- Bone Crypt Tier 4
- Courthouse Tier 4
- Atoll Tier 5
- Chateau Tier 5
- Wharf Tier 5
- Mud Geyser Tier 6

The following maps are priced as Metamorph variant maps in Exilence Next:
- Academy Tier 4
- Caldera Tier 5

(This is a non-exhaustive list, as I only have a small selection out of all the possible location and tier combinations in the game.)

And yes, these are not in fact old maps from previous leagues ingame. Each and every one of them has been earned through gameplay in the month of December - except two: the Coral Ruins and Caldera maps dropped yesterday and today. So that means that on January 2nd, 2021, I received a map as loot that Exilence Next identifies as being from Metamorph league, an entire year and multiple Atlas resets ago.

I have no idea what's going on here, but I hope this helps. If you need anything else from me to narrow it down, I'll gladly help out.

**Comment by viktorgullmark** [comment]
@lOmicronl This should be solved in the upcoming 1.0 release. Please feel free to reopen this if it is still an issue, closing for now. :)

Thanks for your contribution!
