### ISSUE TITLE
NPM Audit Cleanup: Tracking issue for poe-log-monitor npm audit failure

### ISSUE THREAD

**Issue by ambaumann** [viktorgullmark/exilence-next#622]
**Is your feature request related to a problem? Please describe.**
Was looking to run npm audit on the app. Found poe-log-monitor to have some issues. Opened a new ticket there.
Once there is a new release of poe-log-monitor, npm audit should be able to be cleaned up.

**Additional context**
https://github.com/klayveR/poe-log-monitor/issues/10
and closed issue https://github.com/klayveR/poe-log-monitor/issues/6

**Comment by sbsrnt** [comment]
Cleaned up in https://github.com/viktorgullmark/exilence-next/pull/673
