### ISSUE TITLE
when the Auth failed you have no chance to set the session id again! a button with the option renew sessionid was fine!

### ISSUE THREAD

**Issue by Illumant** [viktorgullmark/exilence-next#623]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**
Please provide the version of Exilence Next that you're running.

**Additional context**

**Comment by sbsrnt** [comment]
Indeed, would be handy. 
Until then follow https://github.com/viktorgullmark/exilence-next/issues/591

**Comment by petterannerwall** [comment]
Closing issue by recommendation from @sbsrnt
