### ISSUE TITLE
Can't use the app anymore

### ISSUE THREAD

**Issue by shura300** [viktorgullmark/exilence-next#625]
**Describe the bug**
I open the app, the sectionID is already on, but when the app tries to make a new snapshot, it keeps fetching stash tabs from Hardcore and Softcore Heist. I can't change to Ritual and it was already bugged in Heist.
The app gives a "request failed with status code 400"

**To Reproduce**

**Expected behavior**

**Screenshots**

![Error](https://user-images.githubusercontent.com/77693111/105078589-fb0f8c00-5a6c-11eb-9ca5-0718425ad8c6.png)
![error2](https://user-images.githubusercontent.com/77693111/105078599-006cd680-5a6d-11eb-8df0-83d656b70839.png)

**Version**
v.0.4.2

**Additional context**
Even if I change the league, make a new stash tab, anything... the app still fetch stash tabs from Heist hardcore/softcore.
When I try to make a new Ritual league version, my stash tabs don't show up. (yes, my account config is public)

**Comment by helioborges** [comment]
Yeah, same thing.

**Comment by rulerhao** [comment]
Same thing here.

**Comment by shura300** [comment]
Guys, I think I found the solution... just search %appdata%, go to the folder and than delete the folder "exilence-next-app"
Than just restart your Exilence Next... this should solve...

**Comment by sbsrnt** [comment]
☝🏼 https://github.com/viktorgullmark/exilence-next/issues/591

**Comment by petterannerwall** [comment]
Closing issue by recommendation from @sbsrnt
