### ISSUE TITLE
Can't sign out after 503 error

### ISSUE THREAD

**Issue by Bradders1504** [viktorgullmark/exilence-next#626]
Cannot sign out after a request failure error 503. Which means I cannot reset my session ID.

**To Reproduce**
1. Create an Auth error 503 (Not sure how this originally happened)
2. Click the profile icon next to the notification icon.
3. Try and sign out. Unable to.

**Expected behavior**
Sign out using the button. Then resign back in using my Session ID, stopping the 503 error.

**Screenshots**
https://gyazo.com/86478903b778e4ce7b3570a3478589e3
https://gyazo.com/2f67c60a3afcdce1cafcbb0fc14528cd

**Version**
v.0.4.2

**Additional context**
The only other thing I can think of was that I recently gave Filterblade access to my PoE profile. Could this have affected the session ID and prompted the 503 error?

**Comment by TheChosenOne79** [comment]
I'm having the same issue, just started today.

**Comment by kr0t3** [comment]
same issue.

**Comment by sbsrnt** [comment]
IIRC there was a downtime on Exilence's end that day.
For future reference about signing out - https://github.com/viktorgullmark/exilence-next/issues/591

**Comment by petterannerwall** [comment]
Closing issue by recommendation from @sbsrnt
