### ISSUE TITLE
Can't choose stash in Ritual Leagues

### ISSUE THREAD

**Issue by shinhagunn** [viktorgullmark/exilence-next#627]
![image](https://user-images.githubusercontent.com/77084556/105774995-a00ff480-5f98-11eb-84a0-bdf92799768b.png)

**Comment by Anabolkick** [comment]
I founded your location. Be ready to meet me in real life, scammer.

**Comment by sbsrnt** [comment]
May need to relog / `ctrl+r`

**Comment by petterannerwall** [comment]
Closing issue by recommendation from @sbsrnt
