### ISSUE TITLE
Exilence misidentifies a rare item as a 21/23 Wrath gem.

### ISSUE THREAD

**Issue by krdluzni** [viktorgullmark/exilence-next#628]
**Describe the bug**
Exilence misidentifies a rare shield in my stash as a 21/23 Wrath gem.

**To Reproduce**
1. Have the item in stash.
2. Refresh Exilence.
3. Note the gem showing in the list of items.

**Expected behavior**
Only show items I actually own.

**Screenshots**

![Stash](https://user-images.githubusercontent.com/5222656/106345041-44d15100-627b-11eb-94ea-33553ed49a90.png)
![Exilence](https://user-images.githubusercontent.com/5222656/106345043-4733ab00-627b-11eb-955f-febd9c021027.png)

**Version**
0.4.2

**Additional context**
Exported CSV data for the item:
```
Data from 2021-01-29 21:01

uuid,itemId,name,typeLine,frameType,calculated,inventoryId,elder,shaper,icon,ilvl,tier,corrupted,links,sockets,quality,level,stackSize,totalStacksize,variant,tab,total,max,mean,mode,min,median,detailsUrl,baseType,count
"0182baf0-fdbe-469f-b558-a88297fb0b03","677402af83a5881a76e4e1bc63d13bbe982bab48548f225f2e9b14d24c2c3c71","Wrath","Maple Round Shield",4,81.24,"Stash1",FALSE,FALSE,"https://web.poecdn.com/image/Art/2DItems/Gems/Wrath.png?v=0caa2308df8d3eec2b207f75cc90b05f&w=1&h=1&scale=1",72,0,FALSE,0,1,23,21,1,0,"21/23c",[object Object],81.24,0,0,0,0,0,"https://poe.ninja/challenge/skill-gems/wrath-21-23c",null,22
```

Item copy/paste data:
```
Rarity: Rare
Wrath Rook
Maple Round Shield
--------
Chance to Block: 23%
Armour: 107 (augmented)
Evasion Rating: 88
--------
Requirements:
Level: 39
Str: 52
Dex: 52
--------
Sockets: G 
--------
Item Level: 49
--------
180% increased Block Recovery (implicit)
--------
+9 to Dexterity
+19 to Armour
+98 to maximum Life
19% increased Stun and Block Recovery

```

**Comment by viktorgullmark** [comment]
Thanks for reporting this. However, my conclusion after investigating this is that its not on our end, but at pathofexile.com's end.

- The frametype 4 listed in the data stands for the type Gem, which is a missclassification on GGGs end
- The actual image url is of the wrath gem, and this url is not something we fetch ourself, we simply use the one we get from GGG

With that said, I will try to get this to GGGs attention, so they can update their API accordingly 👍 

Thanks again
