### ISSUE TITLE
ability to calculate rare items

### ISSUE THREAD

**Issue by DirtyNightmare** [viktorgullmark/exilence-next#632]
it could be nice feature to being able to also calculate price of rare items https://www.poeprices.info/ have an awesome api for that

and also it could be nice to being able to price your stuff after different currencies so etc have it all listed as exalted rather than chaos

**Comment by viktorgullmark** [comment]
Thanks for the suggestion. However, we will not price rare items as of right now as we dont agree that its an accurate way of pricing them. 

Regarding the second point we have an open issue regarding this and have it planned for the future. 

Thanks!
