### ISSUE TITLE
PlayStation Support

### ISSUE THREAD

**Issue by DragooNick** [viktorgullmark/exilence-next#633]
I'd love to use your application for playstation.

Right now I can authorize the app after inserting the Session ID. It logs in for a second and then throws me out again with a Error Code 403, but I refreshed the Session ID several times without any change.

Exilence-next v.0.4.2

![grafik](https://user-images.githubusercontent.com/9590675/106874866-5b8e0280-66d6-11eb-8933-9a235ac4cf1a.png)
![grafik](https://user-images.githubusercontent.com/9590675/106874894-62b51080-66d6-11eb-9878-a1c2b9029b48.png)
![grafik](https://user-images.githubusercontent.com/9590675/106874907-65b00100-66d6-11eb-8240-6e5d9bf8dc43.png)

**Comment by TheSithLordDave** [comment]
Having this same problem with the same screens showing but for Xbox.

**Comment by sbsrnt** [comment]
Quite late reply but for future reference: 
1. relog in https://www.pathofexile.com/
2. make sure you copy-pasted new sessid

**Comment by petterannerwall** [comment]
Closing issue by recommendation from @sbsrnt

**Comment by DragooNick** [comment]
That did not work, as stated I did that several times. But as far I found out its because sessid from Playstation Accounts are not supported.
