### ISSUE TITLE
1c Cards

### ISSUE THREAD

**Issue by davoodinator** [viktorgullmark/exilence-next#636]
Yes this has been reported before as a bug. but the fault lies with poeninja reporting 1c prices for 0.2c cards

yes its not "your fault" but its very annoying and a problem that has persisted and has survived from original exilence to current version

can we just have a feature added so we can ignore "1c" cards with a checkmark.   using the minimum value cutoff feature to do this means that properly priced stuff like alterations etc won't get displayed.

**Comment by davoodinator** [comment]
and yes i am aware we can do it "per card" but that is annoying as heck and will destroy the statistics as new cards entering into the stash will get entered in at 1c before we can reprice them manually.

**Comment by viktorgullmark** [comment]
How would you know which cards are actually 1c and which are 0.1c in reality. To me it sounds like the feature you suggest would create a new problem even if it solves the existing one, but the price inaccuracy would still be there but in the opposite way.

**Comment by viktorgullmark** [comment]
Closing for now. I realize its annoying but we dont alter prices from poe.ninja, if you would like to now you would have to do it on a card basis. I will rethink how we could handle this smarter and I understand your frustration with this. Thanks for the suggestion.
