### ISSUE TITLE
see what items you lost/received

### ISSUE THREAD

**Issue by Toasty-chan** [viktorgullmark/exilence-next#637]
**Is your feature request related to a problem? Please describe.**
I'm always so confused when I do 5 maps and my worth rises like 300c. I really wish there was a feature where you can compare your current items to your items like 10 snapshots ago or something, or just 1 snapshot and we can manually reduce snapshot cooldown.

**Describe the solution you'd like**
You fetch tabs, after map tabs get fetched again, all items in new snapshot- items in old snapshot. if you got 2chaos and 10 transmutes or something it will show 2 chaos, 10 transmutes, and -2 chiselz, -1 alchemy orb. etc.

**Describe alternatives you've considered**
I think the solution is plain. new snapshot - original snapshot = whatever you just got and lost

**Comment by viktorgullmark** [comment]
See https://github.com/viktorgullmark/exilence-next/issues/618
