### ISSUE TITLE
Exilence hard crash w/ white screen

### ISSUE THREAD

**Issue by trulysaylt** [viktorgullmark/exilence-next#638]
**Describe the bug**
I had switched to a prior league tab (Tarkehardvibes league), and when it switched exilence hard crashes with a white screen and cannot be interacted with at all. A hard system restart does not solve the issue

**To Reproduce**
Unsure

**Expected behavior**
Give me an error message stating that the league is invalid

**Screenshots**
![image](https://user-images.githubusercontent.com/74740046/108312648-14e3e200-7185-11eb-91c1-7e7d1f1caea0.png)

**Version**
Latest Release (As of 02/18/2018)

**Additional context**

**Comment by trulysaylt** [comment]
I have managed to fix the issue by completely uninstalling exilence via the uninstaller. I then proceeded to reinstall a version which I knew had worked (0.3.1). This let me log back in and launch the app and then it self updated after that.

**Comment by petterannerwall** [comment]
Closing issue by recommendation from @sbsrnt
