### ISSUE TITLE
i cant sign out

### ISSUE THREAD

**Issue by luckys1de** [viktorgullmark/exilence-next#639]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**
Please provide the version of Exilence Next that you're running.

**Additional context**

**Comment by sbsrnt** [comment]
Follow instructions in https://github.com/viktorgullmark/exilence-next/issues/591

**Comment by petterannerwall** [comment]
Closing issue by recommendation from @sbsrnt
