### ISSUE TITLE
Make LeagueDropdown more generic and remove PriceLeagueDropdown

### ISSUE THREAD

**Issue by viktorgullmark** [viktorgullmark/exilence-next#64]
These are essentially the same, with some additional logic in LeagueDropdown. We should rework LeagueDropdown to be more generic and reuse it for listing price leagues, to avoid duplicated code.

Add props as needed.

**Comment by sbsrnt** [comment]
Seems like people from private leagues are using price league dropdowns so I would say we should leave it. And both dropdowns are as simple as they can get
