### ISSUE TITLE
Income card not being reset / updating when clearing all snapshots

### ISSUE THREAD

**Issue by petterannerwall** [viktorgullmark/exilence-next#652]
**Describe the bug**
Income card not being reset / updating when clearing all snapshots

**To Reproduce**

1. Create snapshot
2. Update Profile to change profile value and thus income,
3. Take snapshot again
4. Remove all snapshots 

**Expected behavior**
To have zero income

**Screenshots**
![image](https://user-images.githubusercontent.com/5909669/112836869-6ee89900-909b-11eb-84a8-16d47b97e9bc.png)

**Version**
0.4.3

**Additional context**

**Comment by viktorgullmark** [comment]
Fixed, will be published with the next release.
