### ISSUE TITLE
Missing prophecies in fetched or exported data

### ISSUE THREAD

**Issue by mpoquet** [viktorgullmark/exilence-next#654]
Hi! I'm doing another science experiment around prophecies and I tried to use exilence-next (**0.4.4 release**) to retrieve data from GGG's APIs.

I successfully retrieved my 3 stash tabs but **some prophecies are missing** in the data. I exported the gathered data (with the `Export data` button from exilence-next's  GUI window) into a CSV file, and no field correctly represents the amount of each prophecy I got:
- expected 3 full quad stash tabs, so `12*12*4*3=1728` prophecies
- `sum(stackSize)` = 1481 in exported CSV file
- `sum(mean)` = 1503 in exported CSV file

I may be doing something wrong with exilence-next here but as it looks like a bug to me, I report it here.

I wrote a simple Python script to directly gather data from GGG's APIs, which finds the correct amount of items in my stash tabs. I put in [this gist](https://gist.github.com/mpoquet/ce8ce0fabd95fbd21df70d0c44d54794) the following data:
- The exported CSV file from exilence-next-0.4.4
- The expected prophecy count, as computed by my script
- The JSON data of my tabs, as retrieved from the `https://www.pathofexile.com/character-window/get-stash-items` API

**Comment by viktorgullmark** [comment]
Not sure if I follow entirely, but Exilence will only include items with prices at poe.ninja, so you will have to crosscheck the missing prophecies with that site. 

Let me know how it turns out, will reopen if the problem lies within Exilence, but from your description I doubt it. 

Thanks
