### ISSUE TITLE
Exilence next does not recognises my mirror shard

### ISSUE THREAD

**Issue by Ramonlaw** [viktorgullmark/exilence-next#656]
Exilence next does not recognises my mirror shard

![image](https://user-images.githubusercontent.com/77369336/113993382-cf5da000-982a-11eb-9996-5ca53ae1c667.png)

![image](https://user-images.githubusercontent.com/77369336/113993626-09c73d00-982b-11eb-9e48-d09f602ed1bc.png)

![image](https://user-images.githubusercontent.com/77369336/113993813-34b19100-982b-11eb-9cbb-d6e8d77afbac.png)

**Comment by viktorgullmark** [comment]
Check your price treshold settings and crosscheck with poe.ninja, if still an issue, feel free to reopen.
