### ISSUE TITLE
0.4.6 install not working

### ISSUE THREAD

**Issue by Akkrima** [viktorgullmark/exilence-next#661]
While updating the exe crashed with an error message. Reinstall after deletion is not possible. Showing Error message "Unzip. failed at writing the data Uninstall Exilence next.exe" (german: "Entpacken: Fehler beim Schreiben der Datei Uninstall Exilence Next.exe")

To reproduce, just try to run the exe to install. 

I expected the exe to fully install and run

[url=https://postimg.cc/dZGTsDZs][img]https://i.postimg.cc/dZGTsDZs/Error.png[/img][/url]

Version is 0.4.6

Greetings

**Comment by sbsrnt** [comment]
Thanks for the reported issue!

In case issue still persists - you can try this:
-  first try removing the data from here `C:\Users\user\AppData\Roaming\exilence-next-app` and then try to install new release again
- if you still have the Exilence folder in `C:\Users\user\AppData\Local\Programs\exilence-next-app` and above wont work try uninstalling it manually 
![image](https://user-images.githubusercontent.com/19862545/116014985-02c86900-a638-11eb-8ed2-f77c1a45b8e0.png)

Let me know if above helped.

**Comment by Akkrima** [comment]
Thanks for the fast reply.

I did all the steps as described and it is working fine now.

Tyvm :)
