### ISSUE TITLE
Gem level exp estimator/tracker

### ISSUE THREAD

**Issue by KromBacher1** [viktorgullmark/exilence-next#664]
Would it be possible to get Gem Exp extimator

Approximate gem level up time with approx intervals

**Comment by sbsrnt** [comment]
I doubt that data is available to us but I could be wrong. @viktorgullmark @petterannerwall was any idea like that brought up in the past?

**Comment by viktorgullmark** [comment]
We have talked a bit internally about providing an exp overlay or similar in the future, but doing it for gems is a bit of a stretch honestly. I dont expect us to develop this in the forseeable future, so I will close this.

With that said, its not impossible something similar will be a part of the app in the future.
