### ISSUE TITLE
Initial warning icon during first fetch is permanently present

### ISSUE THREAD

**Issue by sbsrnt** [viktorgullmark/exilence-next#665]
**Describe the bug**
Warning icon is permanently up after initial fetch.
Said user had 18 stash tabs on a 10min interval.

**To Reproduce**
Probably setup as above - large amount of stash tabs with `ctrl+r` to see if the icon sticks until next snapshot.

**Expected behavior**
No icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/19862545/116813855-3fbfbe80-ab56-11eb-9c1f-717b9f1e6a70.png)
![image](https://user-images.githubusercontent.com/19862545/116813940-b65cbc00-ab56-11eb-8499-9a014a79128e.png)

**Version**
0.4.6

**Comment by viktorgullmark** [comment]
Closing, seems to be resolved with the latest update (talked to the guy who initially reported this)
