### ISSUE TITLE
"Failed creating Snapshot - Error binding arguments"

### ISSUE THREAD

**Issue by vklages** [viktorgullmark/exilence-next#666]
I installed the at the moment newest version 0.4.6 on Windows10. I could create an initial snapshot after entering my session-ID and setting up my profile and stash tabs and so on. 
The next time exilence tried to create a snapshot I got the error message 
`Failed creating snapshot - Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked.`
I tried running exilence as administrator (or not) but no change there.
This is my Notifications-Log, if that helps:
![image](https://user-images.githubusercontent.com/12816386/116822045-0fd7e180-ab7d-11eb-8394-c1e91fe6274b.png)

**Comment by fo0bs2** [comment]
Same for me, but I've been using EN on this char for a while.  Looks like 21 existing snapshots, worked earlier today, now this I get the error below on snapshot.  Didn't change anything.  I've updated and still receive the error.

![image](https://user-images.githubusercontent.com/83550952/116822230-b1463f80-ab4b-11eb-869e-07075c39df7c.png)

**Comment by wolfjake-uoft** [comment]
yea I just started getting this error as well

**Comment by viktorgullmark** [comment]
Fixed with the latest update, reopen if still a problem.
