### ISSUE TITLE
Error binding arguments when fetching snapshot

### ISSUE THREAD

**Issue by GeoffreyBalshaw** [viktorgullmark/exilence-next#667]
**Describe the bug**
When fetching snapshots, I get the following error message:
"Failed creating snapshot. Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked."

**To Reproduce**
Scanning in Ultimatum SC league
1. Either manually fetch snapshot or on auto-fetch

**Expected behavior**
Snapshot should be fetched

**Screenshots**
![image](https://user-images.githubusercontent.com/47149397/116822283-06825100-ab4c-11eb-8f2e-619058f9007f.png)

**Version**
v0.4.6

**Additional context**
It looks like price and item data are successfully retrieved, and the error happens in actually creating the snapshot. For reference, the stash tabs it's fetching for are just currency tab, quad tab with some fossils and some random rares, div cards, and essences.
![image](https://user-images.githubusercontent.com/47149397/116822330-4b0dec80-ab4c-11eb-9945-5105cbbdee27.png)

**Comment by fo0bs2** [comment]
I'm getting the same error and notifications.

**Comment by viktorgullmark** [comment]
Fixed with the latest update, reopen if still a problem.

**Comment by GeoffreyBalshaw** [comment]
Seems to be working now, thanks @viktorgullmark !
