### ISSUE TITLE
Failed creating snapshot [ERROR]

### ISSUE THREAD

**Issue by cannibalis** [viktorgullmark/exilence-next#668]
**Describe the bug**
I attempt to fetch a snapshot, and I quickly receive an error upon nearly finishing the creation of the snapshot.

It reads: "Failed creating snapshot. Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked." I have not a single idea what this means.

**To Reproduce**
1. Go to top bar
2. Click on fetch snapshot
3. Wait for it to create snapshot

**Expected behavior**
I expected the application to create my snapshot. It did not, obviously.

**Screenshots**
![image](https://user-images.githubusercontent.com/15465125/116822759-b22ca080-ab4e-11eb-8640-dc7f9230da7b.png)

**Version**
v.0.4.6

**Additional context**
I opened the app up for some grinding this morning, and the app just didn't work. It worked just fine last night, and I made no changes to any of the settings within the application before it stopped fetching snapshots. Googling this issue brings up literally nothing.

I've done everything short of reinstalling. Deleted my profile, reset the application, reset my settings, changed stash tab names, etc. It won't work.

**Comment by Entropygg** [comment]
This is also happening for me as of this morning.

**Comment by viktorgullmark** [comment]
Fixed with the latest update, reopen if still a problem.

**Comment by Entropygg** [comment]
Wow fast response!! Working for me now as expected. Thanks for the fix!

**Comment by cannibalis** [comment]
Thank you very much!
