### ISSUE TITLE
Can't move Exilience Window to 2nd monitor

### ISSUE THREAD

**Issue by petero** [viktorgullmark/exilence-next#669]
**Describe the bug**
I can't move "Exilence-next "window (0.4.8) around, the resize button window next to _ and X doesn't do anything.
This is on Windows 10.Few versions back I could move/resize. 

**To Reproduce**
Just clink on the top black bar to move the window around - it's frozen solid.
**Expected behavior**
The window should be movable between desktop/monitors.

**Screenshots**
![image](https://user-images.githubusercontent.com/539569/117173896-7fdca680-adcd-11eb-98d8-f1507195b38d.png)

**Version**
v0.4.8

**Comment by viktorgullmark** [comment]
Have you tried f11? @petero

**Comment by petero** [comment]
works:) ! thanks. SOLVED.
Might be a good idea to put this into help, for other users.
