### ISSUE TITLE
Snapshot Hotkey

### ISSUE THREAD

**Issue by Dreathorian** [viktorgullmark/exilence-next#674]
Hi I'd like to have a Hotkey for the Snapshot (like ctrl+F8) so I can just have the Overlay open somewhere on screen and refresh it individually after a map/heist etc to know how much that last map/heist got me.

In Addition to that I think difference/delta to last snapshot would be nice to show up as another snapshot, so I don't have to do that calculation in my head.

Should be easy to implement. I hope you give it a go ;-)

Regards,
Christoph

**Comment by sbsrnt** [comment]
Snapshot hotkeys will be obselete after next release. We are switching to new GGG api and it's quite harsh on rate limits so expect snapshot intervals to take a hit.
