### ISSUE TITLE
DataError: Failed to read large IndexedDB value

### ISSUE THREAD

**Issue by Burridil** [viktorgullmark/exilence-next#678]
I get this Message ( DataError: Failed to read large IndexedDB value )  every Time i try to Start Exilence

**Screenshots**
http://prntscr.com/12t04qq

**Version**
v.0.4.8

I got this Problem only on my Main PC, on my Laptop i can run exilence without any problems. 

Sorry for my bad english, ist not my first language.

**Comment by sbsrnt** [comment]
Corrupted data.
1. `ctrl + shift + i`
2. Navigate to `Application` tab
3. Open `Storage > IndexedDB > exilence-next-db -file://`
4. Click `Delete database`

![image](https://user-images.githubusercontent.com/19862545/118380515-957a7900-b5e2-11eb-8ade-c05ff6d38e15.png)
