### ISSUE TITLE
Need a way to delete certain data points from old snapshots

### ISSUE THREAD

**Issue by torsoreaper** [viktorgullmark/exilence-next#685]
I don't know why but I have 1 bad print on my chart where somehow my worth jumps up to 75k chaos (very unlikely), but now my chart is unreadable because the Y axis is completely off.  I can't find any way to delete that 1 bad data point from the net worth chart.  I don't want to delete all my old data, I only want that 1 print deleted.

**Comment by sbsrnt** [comment]
There is something in works for that, though only for latest snapshot.
https://github.com/viktorgullmark/exilence-next/pull/629

**Comment by petterannerwall** [comment]
The backend already have support for deleting snapshots by Id, that's how the delete last snapshot works aswell. The tricky part is a good UI experience and implementation of that.

**Comment by viktorgullmark** [comment]
![image](https://user-images.githubusercontent.com/11405940/136669664-902cab34-7d85-4044-881e-5a6b863c36d5.png)

Done in dev branch, will be live with 1.0
