### ISSUE TITLE
Labels and values not displaying correctly when launching from command line

### ISSUE THREAD

**Issue by rwjmiller** [viktorgullmark/exilence-next#688]
I use a batch file to start PoE and several other associated apps all at once. When I do this I see text in the app like `value.false` rather than just `False`, or e.g. `label.filter_stash_tabs`. The exact invocation I'm using within the batch file is:

`start "" /B /MIN "C:\Users\*****\AppData\Local\Programs\exilence-next-app\Exilence Next.exe"`

It works normally if I uninstall and reinstall the app and launch it via the windows start menu, but if I ever use the batch file to launch it, it persistently behaves as above even when subsequently launching via the start menu.

Is there a way to avoid this behaviour without uninstalling and reinstalling all the time? A command line switch that restores the default behaviour when launching this way would be idea.

**Comment by sbsrnt** [comment]
Fix coming in next release.

https://github.com/viktorgullmark/exilence-next/pull/675
