### ISSUE TITLE
start minimized

### ISSUE THREAD

**Issue by cpbeeker** [viktorgullmark/exilence-next#689]
the feature to start the porgram minimized to the system tray or with a -silent modifier would be wizard!

p.s. a million thumbs up! i was getting about ready to write my own stash parser before I found Exilence-next. Keep it up!

**Comment by viktorgullmark** [comment]
Thanks for your feedback, will leave this issue open and consider adding a setting for it, although it seems very niche.

**Comment by viktorgullmark** [comment]
Decided to close this. I dont feel its worth the effort to add something as niche as this. Sorry to disappoint you!
