### ISSUE TITLE
Implement user defined price fetch intervall

### ISSUE THREAD

**Issue by AllanonTB** [viktorgullmark/exilence-next#693]
Playing on Standard with allot of wealth the short interval of price fetches skews with my net worth.
Quite often i get +3k chaos or -3k chaos with every price fetch cycle so its quite unusable right now for me.
I would like to use an setting (set price fetching to once on app start for example) so the net worth stays stable in my play session.
Im amazed by the app - thanks!

**Comment by dovry** [comment]
![image](https://user-images.githubusercontent.com/15201298/128513110-79565dc1-0286-498d-953f-77b3f0960d68.png)
settings 

This is already in the settings.

**Comment by viktorgullmark** [comment]
Thanks for helping out @dovry. I am closing this issue in lack of response.
