### ISSUE TITLE
Select and add ALL stash tabs instead of adding 1 at a time

### ISSUE THREAD

**Issue by roy-lee** [viktorgullmark/exilence-next#695]
**Is your feature request related to a problem? Please describe.**
It's a hassle to select 1 stash tab at a time when there's over too many to include. 

**Describe the solution you'd like**
The ability to check all stash tabs including "Remove-only". This allows us to know roughly how much is our total net worth especially in standard league.

**Describe alternatives you've considered**
Apart from a "Select all stash tabs", an alternative would be shifting the selected stash to the bottom of the dropdownlist so users can click on the same spot multiple times to add them all.

**Additional Context**
Have seen #554. Maybe we can include a disclaimer to inform users of the slow snapshot time if too many stash tabs are selected.

**Comment by viktorgullmark** [comment]
Right now we have no plans of changing the way this works, in part because of the added serverload to pathofexile.com that this will cause. We do not want to overflood their API substantially at this point, which is why we opted not to have this option.
