### ISSUE TITLE
I logged in a wrong account

### ISSUE THREAD

**Issue by nikotesla01** [viktorgullmark/exilence-next#697]
I was logging in the app for the first time, and I by mistake logged in a wrong account, without any characters in it. Now it just constantly refreshes saying that there aren't any characters "Initialize session failed
a few seconds ago — No characters found for the current account" So now I am trying to log out, and its simply not working as if the option wasn't available.

**Comment by sbsrnt** [comment]
Can you access Settings? If so you can reset the data in Advanced tab there:
![image](https://user-images.githubusercontent.com/19862545/127750253-1ae97487-579c-401b-acf7-15c30dcedb0a.png)
