### ISSUE TITLE
New profile not working

### ISSUE THREAD

**Issue by smithtg6** [viktorgullmark/exilence-next#698]
**Describe the bug**
I created a second profile for a single stash tab and it is not loading anything from that tab.

**To Reproduce**
- Make a single profile that has every tab selected
-  make a second profile with an individual tab and the same settings otherwise
- The second profile is showing nothing

**Expected behavior**
The second tab should show when I switch to that profile

**Screenshots**
Exilence Settings
![image](https://user-images.githubusercontent.com/32054797/127606976-86206fca-fe7e-4d34-99e1-55981667040f.png)
Results when taking snapshot
![image](https://user-images.githubusercontent.com/32054797/127607000-8554a77f-66b6-44be-b0e4-ea76ec56f51a.png)
Tab that has cards
![image](https://user-images.githubusercontent.com/32054797/127607036-90f1fb38-d2ef-498c-89fa-20c45ed3f072.png)

**Version**
v.0.5.0

**Additional context**
This worked fine last league.

**Comment by smithtg6** [comment]
On second glance, it seems to be missing input from that tab completely in the first tab as well.

**Comment by Meldsa** [comment]
Seems to be a problem particulary with divination cards, other types of tabs work fine for me.

**Comment by smithtg6** [comment]
> Seems to be a problem particulary with divination cards, other types of tabs work fine for me.

interesting, thanks for the reply.

**Comment by destoyerrus** [comment]
I have the same problem with metamorph, divination and gem tabs. Gem tab is a normal tab with some gems with quality in it. Before 3.15 exilence worked well with this tabs.

**Comment by sbsrnt** [comment]
> I have the same problem with metamorph, divination and gem tabs. Gem tab is a normal tab with some gems with quality in it. Before 3.15 exilence worked well with this tabs.

I'm gonna need more info about the metamorph and gem tabs as I don't have any issues with boths.

Did you set any thresholds in settings besides defaults that are not showing in pricing table? Did you try moving out items from said tabs into other tabs to see if they show in other tabs?

**Comment by sbsrnt** [comment]
Fixed in [v.0.5.1](https://github.com/viktorgullmark/exilence-next/releases/tag/v0.5.1)
