### ISSUE TITLE
0.5.0 Div Cards No Longer Showing

### ISSUE THREAD

**Issue by dcgaines** [viktorgullmark/exilence-next#699]
Even when my Div Card tab is selected in my profile for Expedition SC league, they are not showing in the net worth calculations. The other tabs (currency, delve, fragment, essence) are working.

**Version**
This was working a few days ago, I believe after I updated to 0.5.0 but I am not positive. I am currently running 0.5.0 and it is not working.

**Comment by D3luxe** [comment]
Can confirm mine also is not reading my div card tab after 0.5.0 update

**Comment by destoyerrus** [comment]
I have the same problem with metamorph, divination and gem tabs. Gem tab is a normal tab with some gems with quality in it. Before 3.15 exilence worked well with this tabs.

**Comment by LunarBear** [comment]
Confirming same issue.

**Comment by Shadowclaimer** [comment]
Confirming for myself and another.

**Comment by DoctorPlague** [comment]
Confirming same issue here. Have taken all steps I could think of to rectify including resetting data, etc.

**Comment by wturney** [comment]
Looks like the code is index checking the icon URL for divination cards and prophecies in `pricing.service.ts` (e.g. `p.icon.indexOf('Divination') > -1`) and those URLs point to a CDN without that information now. Short term fix you could use `p.detailsUrl.indexOf('divination')` etc when available.

**Comment by sbsrnt** [comment]
Fixed in 0.5.1
