### ISSUE TITLE
Few quality of life features that I feel should be added, and should also help community.

### ISSUE THREAD

**Issue by PrototypeRak** [viktorgullmark/exilence-next#706]
**Is your feature request related to a problem? Please describe.**
Not related to any problem

**Describe the solution you'd like**
A) When new prices/snapshot is fetched, Exilence should show which item dropped and which item went up in price. We can have another column in there that shows previous price and new price, and can have them color coded, or have down/up arrow graphics or have separate filters to filter out based on if the price went down or if the price went up. As we already have current price/snapshot, and with periodic future price / snapshot fetch,  we can show the difference between these two. This feature can be refined further to setup thresholds in settings, which let us take action (may be an alert or just color coding the item row in Red or something)  if the price went up or down beyond the threshold limit defined within a certain period of time. This would let users know which items should be sold quickly and which ones should be kept for longer periods of time to increase profit. 
For ex. an item that over a period of time shows constant increase in price, it would make much sense to sell it when the price gets saturated whereas if price on an item would fall down a certain threshold within a period of time, like for ex. 10 chaos in 2 hours, it would make sense to sell it ASAP to avoid losses.  
Of course when I type this, I find it a little funny since we are talking about currency inside of a game, but I hope you get my point!! lol

B) TAB breakdown chart should go full screen or at least pop out to bigger size when you click on it. Clicking on any of the tab graphs should only show the items that belong to that tab and also with above functionality mentioned in (A)

Again these are quality of life features and should improve overall user experience in my honest opinion. 

You guys do fantastic job as always, and wish you all the very best!

**Describe alternatives you've considered**
I usually refer to trends on POE.NINJA to derive these decisions

**Additional context**

**Comment by viktorgullmark** [comment]
@PrototypeRak Thanks for your feedback. We will start with something like this for the item table, to showcase the price history:

![image](https://user-images.githubusercontent.com/11405940/136183628-88956efb-d5c7-4f82-8b81-c8cad6b12f98.png)

Changes between snapshots will come later, since we only store the items for the last snapshot, since it would bloat a lot of memory if we decided to keep historic snapshots on the client. We have some plans for this later, but at this time we cant do much in that area.

**Comment by PrototypeRak** [comment]
Thank you for considering these changes. Cannot wait to try out the new changes in upcoming league!!

All the very best.

Thank you
Jitender Singh


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
