### ISSUE TITLE
Map tab missing

### ISSUE THREAD

**Issue by sjurado** [viktorgullmark/exilence-next#707]
**Describe the bug**
I'm trying to price check a few tabs but somehow my map stash tab is missing. I've reinstalled several times, even deleted everything inside %APPDATA% related to Exilence but still I'm not able to see that particular map tab. I can see all the others, but not that particular one.

**To Reproduce**
1. Create a new profile
2. Pick Expedition pricing league
3. Pick Expedition league
4. See map stash tab missing from the list of stash tabs

**Expected behavior**
Should see all stash tabs.

**Screenshots**

![ingame map stash tab](https://i.imgur.com/o3EqpmN.jpg)

![exilence next](https://i.imgur.com/3JjNxZq.png)

**Version**
Latest v0.5.1

**Comment by sbsrnt** [comment]
Maybe one day it will be here.

Until then - https://github.com/viktorgullmark/exilence-next/issues/533#issuecomment-618847677
