### ISSUE TITLE
Exilence doesn't work after 0.5.2 and 0.5.3 - creates ghost processes 

### ISSUE THREAD

**Issue by pvtri96** [viktorgullmark/exilence-next#710]
**Describe the bug**
After I setup the app on windows 11, the app cannot start.

**To Reproduce**
1. Go to release page
2. Click on download latest build.
3. Install the setup file.
4. App UI does not show up.
5. In Task Manager, the application is taking 50mb of memory and nothing else

**Expected behavior**
Shouldn't it be able to run on Windows 11?

**Screenshots**
![image](https://user-images.githubusercontent.com/28696888/129055632-67094ba2-3eb6-441e-90a3-3059e5bc0a00.png)

**Version**
0.5.2

**Additional context**
None.

**Comment by vioxin** [comment]
This isn't limited to Windows 11, having the exact same result on Windows 10. App never appears, just uses a small amount of memory and says it's running.

**Comment by sbsrnt** [comment]
We are aware of this issue after todays release. Downloading [0.5.1 version](https://github.com/viktorgullmark/exilence-next/releases/tag/v0.5.1) and upgrading it fixes that. Not sure what caused it as I didn't have much time today to investigate

**Comment by pvtri96** [comment]
I can get it working now. Many thanks. Do you need to keep this issue around, or close it?

**Comment by Verttox** [comment]
0.5.3 still behaves in this way for me.

Creates ghost process but never actually opens.

**Comment by darkphoenix6259** [comment]
Problème pour moi aussi il ne veux pas s'ouvrire même avec les droit admin, mes toujours en fantôme dans ma barre des taches

**Comment by n-irwin** [comment]
0.5.3 still behaves in this way for me as well.

Creates ghost process but never actually opens.

**Comment by sbsrnt** [comment]
> Problème pour moi aussi il ne veux pas s'ouvrire même avec les droit admin, mes toujours en fantôme dans ma barre des taches

Buddy, we don't speak French here. Please stick to english.
