### ISSUE TITLE
Unable to run on Windows 10

### ISSUE THREAD

**Issue by Drew-Alleman** [viktorgullmark/exilence-next#711]
**Describe the bug**
Unable to launch Excellence Next after installation

**Expected behavior**
The program should launch after running Excellence-Next

**Version**
Latest (0.5.2)

**Additional context**
I disabled my AV and reinstalled the application and the bug persists. It says the program is running in task manager, however no window appears. I tried installing 0.5.1, but the same thing happened. 
Microsoft Windows 10 Home. Version 10.0.19043 Build 19043

**Comment by LiiMooTBM** [comment]
Same issues here as well. Installed first yesterday with 0.5.2. Installing works, but the app doesn't start. In the task manager, you can see the process running.

**Comment by MegaKruk** [comment]
Same issue here! Installation goes without problems. Launching the app launches the process correctly as seen from Task Manager. It's just the process doesn't seem to actually do anything. Literally nothing outside of process just launching happens. No errors pop up, no windows pop up, literally nothing. 

Version
Latest (0.5.2)

Windows 10 Education Version 21H1 OS Build 19043.1110

**Comment by sbsrnt** [comment]
duplicate - https://github.com/viktorgullmark/exilence-next/issues/710
