### ISSUE TITLE
App is not working

### ISSUE THREAD

**Issue by vdomi92** [viktorgullmark/exilence-next#714]
**Describe the bug**
App does absolutely nothing. Just creates ghost processes, but is not doing anything at all.

**To Reproduce**
1. Install app
2. Launch exe
3. ????

**Expected behavior**
Does more than showing 4 current tasks in task manager.

**Version**
0.5.3

**Comment by sbsrnt** [comment]
https://github.com/viktorgullmark/exilence-next/issues/710
