### ISSUE TITLE
"The Tempestuous Steel" matches for "The Tempest"

### ISSUE THREAD

**Issue by ManuelHirsch** [viktorgullmark/exilence-next#715]
**Describe the bug**
In the list of items I own, it shows 2 "The Tempest". But one is acutally "The Tempestuous Steel". The search needs to be anchored.

**To Reproduce**
1. Start program while you own both
2. Login/Scan/...
3. Scroll down to "The Tempest"
4. It shows 2x the Tempest although one is the above sword.

**Expected behavior**
Names match correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/2880091/129343414-5b0782a8-afaf-4240-aa94-5868ecb5e2a3.png)
![image](https://user-images.githubusercontent.com/2880091/129343569-061e957b-9f7e-4cd8-856d-5d906a0d0c08.png)

**Version**
0.51

**Additional context**

**Comment by sbsrnt** [comment]
@viktorgullmark this looks like API issue from GGG nay? 🤔just like we had a shield that had `wrath` in the name but it was listing `wrath` gem

**Comment by viktorgullmark** [comment]
@sbsrnt True, not impossible. Could also be the way we look up items on our end, but will have to rule that out and compare with the GGG API first, and report this to them if its on their end.

**Comment by viktorgullmark** [comment]
Will be live with next release, thank you for the bug report!
