### ISSUE TITLE
New User - Program is not displaying when running

### ISSUE THREAD

**Issue by Saga-** [viktorgullmark/exilence-next#716]
**Describe the bug**
Program will not display while running after being installed on Windows 10.

**To Reproduce**
Steps to reproduce the behaviour:
1. Uninstall any previous versions
2. Download and run the installer executable 
3. [installer should run and complete]
4. Program is running, but no window is displaying. Subsequent executions make no difference

**Expected behavior**
Exilence window should display if it is running

**Screenshots**
n.a.

**Version**
0.5.3 (tried 0.5.2 as well)

**Additional context**
Initially I thought my firewall may be preventing the application from running, but upon disabling my firewall and reinstalling Exilence it makes no difference. I saw the release notes for the version and thought I should raise this issue.

**I just installed v0.5.1 and it works**

**Comment by sbsrnt** [comment]
@Saga- Your timing is really unlucky as we have just disabled 0.5.2 and 0.5.3 versions since they are, as you have noticed, bricked.

We just released [0.5.4](https://github.com/viktorgullmark/exilence-next/releases/tag/v0.5.4) that fixes this issue.

**Comment by sbsrnt** [comment]
Actually I'm just gonna keep the issue open for the next few days for visibility.

**Comment by sbsrnt** [comment]
Closing as there are no more issues related to this post.
