### ISSUE TITLE
Loggin button don't work

### ISSUE THREAD

**Issue by ShrarksGx** [viktorgullmark/exilence-next#717]
**Describe the bug**
The button of login is not working

**To Reproduce**
1. Open exilence v.0.5.5
2. A Whithe screen for 5 sec
3. Click on 'Log in with pathofexile.com'
4. And nothing, without error message

**Expected behavior**
Loggin and use the program

**Screenshots**
Na

**Version**
V.0.5.5

**Additional context**
I tryed to use any other button (discord and patreon) and nothing works, dosn't open any

**Comment by sbsrnt** [comment]
Can you `ctrl + shift + i` and provide a screenshot of what errors you get when you navigate to console?
![image](https://user-images.githubusercontent.com/19862545/129416838-56766ba7-fdeb-41f6-bdd7-7bdf8f649229.png)

**Comment by ShrarksGx** [comment]
There is the screenshot
![image](https://user-images.githubusercontent.com/88905537/129418707-8881ad49-1173-427c-be0f-de219bb2ac3f.png)

**Comment by sbsrnt** [comment]
Well thats weird - did you try reinstalling exilence? Or maybe if that won't work either then perhaps maybe `0.5.4` or `0.5.1` versions may work https://github.com/viktorgullmark/exilence-next/releases

**Comment by ShrarksGx** [comment]
v.0.5.1 
![image](https://user-images.githubusercontent.com/88905537/129421135-ed784e51-d59b-4516-8d77-78842da09292.png)
v.0.5.4 
![image](https://user-images.githubusercontent.com/88905537/129421313-e64c27de-23a3-4dfb-b76f-3ca6873aa1e2.png)

The first thing i tryed is reinstall :c 
These versions don't have the white screen in the start, but still don't works the login button

**Comment by sbsrnt** [comment]
I suggest joining our discord for faster responses https://discord.gg/SetMPZqF and maybe you may find someone who had a similar issue in the search

**Comment by ShrarksGx** [comment]
Solved, the problem is use chrome as pred navigator. 
Work fine with Firefox and Edge
Thx for the help. <3
