### ISSUE TITLE
[Low Priority Bug] "Unknown Publisher"

### ISSUE THREAD

**Issue by conetopia** [viktorgullmark/exilence-next#725]
Windows 11 keeps popping up with the fallowing , same with windows 10.
"Unknown Publisher"
when trying to download/run the file.

[Security] windows defender/smart-screen popup.

**Comment by viktorgullmark** [comment]
Not a bug. Its related to us not having a code sign certificate. Since this is a free app we do not plan to buy one at this time, since they are not very cheap last I checked.
