### ISSUE TITLE
The price of Blighted map is pulled from regular maps on poe.ninja. 

### ISSUE THREAD

**Issue by Antorell** [viktorgullmark/exilence-next#726]
**Describe the bug**
Blighted maps in the application display price from the regular maps (old league maps) instead of the appropriate similar Blighted map.  

**Expected behavior**
Link and pull the correct price from the the correct Bligted map on poe.ninja

**Screenshots**
![Capture](https://user-images.githubusercontent.com/25066224/133843739-56134208-a9a1-4969-b2da-298c8fb87d16.PNG)

Both maps link to some older map when I click on the link icon to check the map on poe.ninja
https://poe.ninja/standard/maps/racecourse-map-t14-gen-11
https://poe.ninja/standard/maps/dunes-map-t15-heist

**Version**
Exilence-Next 0.5.5

**Comment by viktorgullmark** [comment]
Thanks for your feedback. Can you test this in the latest release, 0.6.0? If it is still an issue, please reopen and we will take a look!

**Comment by Antorell** [comment]
The update didn't fix the issue. 

 
![Capture](https://user-images.githubusercontent.com/25066224/133945003-521a4b25-079b-4250-bed9-4413aa78b708.PNG)

**Comment by Antorell** [comment]
I just looked up the code and I couldn't find any mention of any sort that separate a blighted map from a regular map from what's downloading from the user profile on the path of exile's website. Might be why it's pulling prices of normal maps on poe ninja.
