### ISSUE TITLE
The price of Blighted map is pulled from regular maps on poe.ninja. [reopened bug report]

### ISSUE THREAD

**Issue by Antorell** [viktorgullmark/exilence-next#727]
**Describe the bug**
Blighted maps in the application display the price of regular maps (old league maps) instead of the similarly named Blighted map.  

**Expected behavior**
Link and pull the correct price from the the correct Blighted map on poe.ninja

**Screenshots**
![Capture](https://user-images.githubusercontent.com/25066224/133843739-56134208-a9a1-4969-b2da-298c8fb87d16.PNG)

Both maps link to some older map when I click on the link icon to check the map on poe.ninja
https://poe.ninja/standard/maps/racecourse-map-t14-gen-11
https://poe.ninja/standard/maps/dunes-map-t15-heist

![Capture](https://user-images.githubusercontent.com/25066224/133945208-796f04cd-f646-4738-be5c-8832c3de6fe2.PNG)

The issue isn't resolved in version 0.6.0

**Version**
Exilence-Next 0.6.0

**Comment by viktorgullmark** [comment]
Thanks, we will have to rework how maps are parsed. Will leave this bug report open.

**Comment by viktorgullmark** [comment]
@Antorell This has been fixed and will be live with 0.6.1. Expect the release sometime during next week since we need to update our backend accordingly.

![image](https://user-images.githubusercontent.com/11405940/134347243-004c7dce-5b6f-43da-bf9d-1cc3c9cd1f23.png)

**Comment by viktorgullmark** [comment]
Closing for now, please reopen or contact me directly on Discord if still an issue in 0.6.1 and I can help through there! (Discord link in README.md)

**Comment by Antorell** [comment]
Awesome, thanks.
