### ISSUE TITLE
Add support for poe.watch as price source

### ISSUE THREAD

**Issue by viktorgullmark** [viktorgullmark/exilence-next#73]
Currently we only support poe.ninja as price source. For more detailed data we should allow usage of poe.watch (probably as default). 

See `profile.ts`  and `priceStore.leaguePriceDetails` for how sources work today.

**Comment by git42leech** [comment]
This would fix #470!

**Comment by viktorgullmark** [comment]
Yea, seems that way. Thanks for enlightening us! @git42leech
