### ISSUE TITLE
Adding a large amount of stash tabs one by one is slow, clunky, and frustrating

### ISSUE THREAD

**Issue by Amythir** [viktorgullmark/exilence-next#759]
It is very slow, clunky, and frustrating to add a large number of stash tabs to a profile.

The use-case that pushed me over the edge is trying to create a profile for my standard stash because I was curious what items I have and what the most expensive item I own is and my total standard networth. I have 370 or so stash tabs in Standard from years of remove-only tabs accumulating.

I recognize this is an extreme case, but it revealed a frustrating user experience. See my video below:
https://i.gyazo.com/663ae0f7f122072a99277f3cf18e0d45.mp4

And I want to note that this is only trying to add 30 tabs. The more tabs you add, the more the field at the top grows to the point where I can only see like 2 tabs at a time, I have to scroll down, click a few more tabs, field grows, see less tabs, scroll, add more tabs, rinse repeat.

The size of the field should never change because you're moving elements unpredictably while users are trying to click on something.

My solution:
Abandon this method of adding stash tabs one by one. Pull up a list of all the stash tabs for a given circumstance, eg expedition tabs, and put a tick box next to them for bulk adding stash tabs.

Use-case would then look like this: Select League -> Expedition -> List of Tabs with tick marks -> Tick all the boxes to add -> click bulk-add tabs -> done

**Comment by sbsrnt** [comment]
Sucks to be you then buddy.

To give you a bit of a context why large amount of stashes is bad and why people like you are where we are at now - this is borderline DDoSing poe.ninja and GGG servers. Period.

You may ask `why?`

 With `character-window` API, so what you see in your stash on GGG website, we were allowed with lucrative 200 requests / 2 minutes. This is getting depracated by GGG for obvious reasons - it's burning a lot of unnecessary money on their end for no gain. 

With new API the limits have been colossally (and this is still an understatement as you have noticed) reduced. 

I will let you translate this message for me in case you didn't notice:
![image](https://user-images.githubusercontent.com/19862545/137104950-c30b1558-8053-4238-b1ad-e15b8b38a82f.png)

I will also like to mention that each map you have in your map stash is counted as separate stash. So if you have let's say 160 maps, then you actually have 370+160 stashes.
