### ISSUE TITLE
Guild Stash

### ISSUE THREAD

**Issue by Kapsonfire-DE** [viktorgullmark/exilence-next#777]
Can we add a Feature to check the Guild Stash as well? I'm having a guild with my wife and we are sharing everything with the guild stash tabs.

**Comment by stephenseiber** [comment]
i agree it is a pain moving a bunch of maps and divinations to my stash to figure out how much they are worth

**Comment by KuryKat** [comment]
Same issue here, I'd love to be able to see the guild stash, playing with my gf and we share everything

**Comment by viktorgullmark** [comment]
Not possible to add until GGG adds it in their API. https://www.pathofexile.com/developer/docs/reference
