### ISSUE TITLE
Rain of Chaos Divination Card Incorrect Pricing/Valuation

### ISSUE THREAD

**Issue by Skittleeez** [viktorgullmark/exilence-next#778]
**Describe the bug**
Rain of Chaos is priced as 1 Chaos Orb rather than (1/8)th of a Chaos Orb

**To Reproduce**
1. Add a Divination Tab to a profile (Regular tab might work as well)
2. Take Snapshot
3. Look at Price and Total Value column

**Expected behavior**
8 Rain of Chaos can be redeemed for 1 Chaos orb, so the item should be individually priced at (1/8)th of a Chaos Orb.

**Screenshots**
![Screenshot (90)](https://user-images.githubusercontent.com/93393465/139463073-875024ce-cff0-4bac-b1e2-01e32a314c2a.png)

**Version**
v.1.1.5

**Comment by viktorgullmark** [comment]
This is not a bug. If you feel the price is wrong you can override it in the settings, but we are using prices from https://poe.ninja, and do not price anything ourselves.
