### ISSUE TITLE
Maps not getting price checked

### ISSUE THREAD

**Issue by rakataka123** [viktorgullmark/exilence-next#780]
**Describe the bug**
Maps wether in map tab, premium stash tab or quad stash tab don't get price checked.

**To Reproduce**
1. Dump maps in premium tab, quad stash tab or map tab.
2. Check corresponding tabs in Exilence Next under your profile.
2. Take snapshot.
3. No maps are listed in Exilence Next.

**Expected behavior**
Since the map tab behaves like 160 stash tabs price checking maps in this tab should take a while because of GGG's restriction regarding the fetching of 30 tabs/5 min. Dumping maps in premium tabs should be a workaround since it only counts as one tab. By taking a snapshot I expect Exilence Next to fetch the prices of maps lying around in the checked premium tabs and list them in Exilence Next.

**Screenshots**
![Bug1](https://user-images.githubusercontent.com/93386058/139527384-706d2dd0-8dc1-445a-bfc1-8195510d3ba5.png)

![Bug2](https://user-images.githubusercontent.com/93386058/139527386-3ab2cc4a-6e30-42d0-b17c-d3b4bf0a831c.png)

The first picture shows that no prices were fetched for premium tab 1 while the second picture clearly shows that there are maps in premium tab 1 that could be price checked.

**Version**
Exilence Next v.1.1.5

**Additional context**
-

**Comment by viktorgullmark** [comment]
Solved in 1.1.6, reopen if still an issue
