### ISSUE TITLE
My app has an unstable blurry display somehow, don't know why

### ISSUE THREAD

**Issue by XstormLeigh** [viktorgullmark/exilence-next#786]
It runs really smooth on the laptop at home, but it seems not displaying so well on the laptop in my office. App is displaying blurry when my mouse is not on top of certain areas, when but when I move my mouse on top of the blurry part, it is clear again. Does anyone else experience similar issue with the app
![微信截图_20211107160735](https://user-images.githubusercontent.com/49313930/140637392-93c4eb7f-03fc-4161-a044-2827b43f3d25.png)
?

**Comment by viktorgullmark** [comment]
This is related to your graphics drivers. Try doing a fresh install of these.
