### ISSUE TITLE
Ignore items below a certain price when creating a snapshot

### ISSUE THREAD

**Issue by tbarusseau** [viktorgullmark/exilence-next#788]
**Is your feature request related to a problem? Please describe.**
Currently, if you snapshot something like a map or uniques tab, you'll end up with a huge amount of 1c/1alch items, that you'll probably never realistically sell.

**Describe the solution you'd like**
An additional option in the profile's settings were we can set below which price we don't want items to be added to our net worth.

**Additional context**
I know that the initial idea is to measure total worth, but I'm personally using the application to know how much I can get if I sell everything listed in the configured stash tabs. But I'll never sell anything under 2c, so the final result doesn't really represent how much I really have (since these tons of 1alch/1c/2c items add up).

Thanks, awesome software 👍

**Comment by Tomagathericon** [comment]
There's literally a setting like this in the options already. 
[img]https://i.imgur.com/OmsoAaO.png[/img]
Bottom right.

**Comment by tbarusseau** [comment]
Thanks. I somehow didn't see it, my bad! I thought it made more sense to look into the profiles' settings, but it's more logical in the global settings.
