### ISSUE TITLE
Stuck on Maximized Mode

### ISSUE THREAD

**Issue by takoz53** [viktorgullmark/exilence-next#792]
Maximizing / Minimizing keeps staying on maximized mode whatsoever. Can't drag window around / make it smaller.

[Video describing the issue](https://puu.sh/IpFMY/2093c95fa2.mp4)

**Comment by sbsrnt** [comment]
For future reference:

Try clicking `F11` (fullscreen mode) and `F11` back.

---

seems to be rare issue with electron
people happened to experience that with electron and other similar apps
https://support.discord.com/hc/en-us/community/posts/360062461212-Cant-drag-the-window-from-the-very-top
