### ISSUE TITLE
Stuck on Fetching special tabs

### ISSUE THREAD

**Issue by Frostbird1** [viktorgullmark/exilence-next#793]
It takes upwards of 10 minutes to fetch prices and update just a few tabs. Any solutions? Also i haven't been spamming taking snapshots so i don't think i'm being rate limited.

**Comment by viktorgullmark** [comment]
Countless messages about this in our Discord, you are being ratelimited because of the way map tab currently works. Its not on our end, its a limit on pathofexile.com sadly. Closing

**Comment by viktorgullmark** [comment]
https://github.com/viktorgullmark/exilence-next/issues/793
