### ISSUE TITLE
Prices are stuck on standard?

### ISSUE THREAD

**Issue by davidponton** [viktorgullmark/exilence-next#805]
**Describe the bug**
The breakdown for my networth uses standard prices, not league prices, even though I have it set to use Archn

**To Reproduce**
Dunno, just downloaded it, took a snapshot and it showed my prices in standard. Didn't really do anything special.

**Expected behavior**
Prices should be based on League prices.

**Version**
1.1.7

**Additional context**
I made sure that the settings are set to Archnemesis.

**Comment by viktorgullmark** [comment]
Follow the tutorial again, press the ? in the top right. Look into profiles.
