### ISSUE TITLE
Unable to select new league or see characters/stash tabs

### ISSUE THREAD

**Issue by Madzterzs** [viktorgullmark/exilence-next#808]
**Describe the bug**
When setting up a new profile, I am able to see the Archnemesis league under the Select Pricing league option but not under the Select League option. Only Standard league shows in the Select League field. Therefore I am unable to select my Archnemesis league characters or see their stash tabs. Even with Standard league selected there is no data coming through when selecting Standard league. 

**To Reproduce**
1. Click on Create Profile
2. Set the 'Select Pricing League' to Archnemesis
3. Select the 'Select League' field and only see Standard in the list of options.
4. Select Stash Tabs only shows 1,2,3,4 as options
5. Select character only shows some of my Standard league characters.

**Expected behavior**
I expected the option to change the  'Select League' field to Archnemesis league but this option is not listed.

**Version**
v.1.1.7
![EX1](https://user-images.githubusercontent.com/99622812/153784192-726fce2f-c691-4d9f-aa43-165badb47c90.png)

Perhaps I am misunderstanding how this should work?
Thanks!

**Comment by Madzterzs** [comment]
Just to add to this, I have reinstalled the app several times. I have restarted my pc after every installation. I have also been through the web and cannot see a related issue. I have also used the RESET DATA option in the app. Thx

**Comment by sbsrnt** [comment]
@Madzterzs 
Is this still an issue?

**Comment by Madzterzs** [comment]
Unfortunately yes. I have been trying every day with no success. 
Am I understanding this correctly as explained above? 
Should I see an option for Archnemesis league in the 'Select League' field'?

**Comment by Madzterzs** [comment]
Problem solved guys. I didn't realise I had more than one POE account and for some reason the POE site had my older account's credentials stored. And as I have not played on this account this league, the new league name is not showing on the list above. All sorted. Thanks!
