### ISSUE TITLE
Snapshot failing since last patch

### ISSUE THREAD

**Issue by cooperaustinj** [viktorgullmark/exilence-next#810]
**Describe the bug**
When a snapshot is attempted, this error shows:
`Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked.  `

**To Reproduce**
1. Click Take Snapshot
2. Wait for stash tabs to be loaded
3. An error toast shows with the above message
4. No items are updated; seems the snapshot fails entirely.  Doesn't seem to be an API issue since the stash tabs seem to be downloading.

**Expected behavior**
A snapshot will be taken.

**Version**
1.1.7

**Comment by cooperaustinj** [comment]
FYI, I'm setting up locally to see if I can resolve this.

**Comment by talerzdebi** [comment]
Same to me. Thought its because i had too many stashes.

**Comment by cooperaustinj** [comment]
Removing Charged Compasses from the currency tab (or maybe all snapshotted tabs) is a workaround.

I've stopped looking into the issue.

**Comment by eloluap** [comment]
Had the same problem, was able to resolve it with removing the charged compasses from the currency tab.
Thanks for suggesting that @cooperaustinj.

**Comment by viktorgullmark** [comment]
I think we fixed this in one of the latest versions, will close for now. Reopen if this still occurs
