### ISSUE TITLE
Exilence Next failing to create snapshot since 3.17.1

### ISSUE THREAD

**Issue by prothocrice** [viktorgullmark/exilence-next#811]
**Describe the bug**
Getting an error that reads:
"Failed creating snapshot - Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked."
Has been this way since the 3.17.1 update, hasn't worked once.

**To Reproduce**
Happens any time the program tries to create a snapshot.

**Expected behavior**
The snapshot to work as intended.

**Screenshots**
![Screenshot 2022-02-19 154404](https://user-images.githubusercontent.com/27863423/154820151-98929320-4cfa-4241-8794-a555170324b5.png)

**Version**
Please provide the version of Exilence Next that you're running.
v1.1.7

**Additional context**
N/A

**Comment by ctmendez941** [comment]
This happens if you try to snapshot any tabs with charged compasses in them

**Comment by joe-angell** [comment]
Thanks, have the same issue.

**Comment by DeckStarg** [comment]
I have removed all charged sextants from tabs and still get an endless cycle of "Fetching Stash Tabs"

**Comment by gmeral** [comment]
> This happens if you try to snapshot any tabs with charged compasses in them

Can confirm that after removing the charged sextants i did not have the error

**Comment by sbsrnt** [comment]
Keep in mind that other items that are in the stash where `Charged Sextant` is are being priced correctly. Error may look misleading, but only `Charged Sextant` is not being priced/listed.

**Comment by viktorgullmark** [comment]
I think this is sorted out now, feel free to reopen if this still occurs.
