### ISSUE TITLE
Add the ability to hide/filter out row entries below a chaos value threshold per item or per stack.

### ISSUE THREAD

**Issue by Discipol** [viktorgullmark/exilence-next#817]
**Is your feature request related to a problem? Please describe.**

When using quad tabs with lots of small things like rings / amulets / jewels, most of them are of ~2 chaos worth and I would love it if I could filter them out.
Same concept, but for divination tab, I want to filter out the 1-2c ones (or a chaos value I input).

**Describe the solution you'd like**
A button where I can hide/filter out entries in the row list that are above my minimum value. Would be nice if I could set it for each individual item, or for the stack itself.

**Describe alternatives you've considered**
Force my POE loot filter to hide those items, but I am a compulsive looter and you never know what value has at a glance, hence my dump tabs.

**Additional context**

**Comment by viktorgullmark** [comment]
This exists in the settings, if I understand you correctly. Feel free to reopen if I am wrong

**Comment by Discipol** [comment]
@viktorgullmark It was indeed, under the name threshold. I just expected it per profile instead of in the settings.
Thanks for making the tool, it made me a lot of ex via cards i didnt know I had and could sell, like a doctor lol
