### ISSUE TITLE
Endless Fetching special tabs ....

### ISSUE THREAD

**Issue by ParanoiaIsGreat** [viktorgullmark/exilence-next#819]
**Describe the bug**
Endless Fetching special tabs ....

**To Reproduce**
Just use this and that happens.
I don't know why..

**Expected behavior**
Normally use.

**Screenshots**
![image](https://user-images.githubusercontent.com/10475153/155867130-63414d77-f46b-42d7-99d3-350dcaf04a5f.png)

**Version**
1.1.8

**Additional context**

**Comment by viktorgullmark** [comment]
Closing, do a search in our Discord or look at the (i) icon
