### ISSUE TITLE
Allow inclusion of Heist and Expedition lockers to profiles

### ISSUE THREAD

**Issue by Sunscorcher** [viktorgullmark/exilence-next#820]
**Is your feature request related to a problem? Please describe.**
If I want to include rogue markers, blueprints, logbooks, etc. in my shapshots, then I cannot use those lockers.

**Describe the solution you'd like**
It would be nice to be able to select the Heist and Expedition lockers in the stash tab dropdown when creating a profile.

**Comment by viktorgullmark** [comment]
We only price the same categories as poe.ninja does. https://poe.ninja/

If there is any category that they price on poe.ninja that we dont, let us know and we will sort it out!
