### ISSUE TITLE
Unable to change Auto Snapshot interval below 5 minutes

### ISSUE THREAD

**Issue by Valsitsar** [viktorgullmark/exilence-next#831]
**Describe the bug**
The text field won't allow for a number lower than 5 as the first digit; if such first digit is entered, the program won't allow for deletion of the second (or any subsequent) digit(s). Furthermore, it won't allow for deletion of all digits.

**To Reproduce**
1. Go to 'Settings',
2. Click on 'Set auto snapshot interval' text field,
3. Try to erase all digits,
4. Try to rewrite the number of minutes to a number lower than 5.

**Expected behavior**
Upon pressing Backspace, delete appropriate letters and/or numbers.
Upon highlighting the text in the text field and pressing appropriate keys, rewrite/modify the value in the text field.

**Version**
Exilence Next v.1.1.8

**Comment by sbsrnt** [comment]
Intended. You will get rate limited by GGG to oblivion otherwise and that will become quickly frustrating.
