### ISSUE TITLE
Cant log in

### ISSUE THREAD

**Issue by Haulm121** [viktorgullmark/exilence-next#832]
Hi!

If i try to log in it gives me 403 error. I find a detail in the faq how to repair it. I reset my session id, and it gives error messeges again.

![image](https://user-images.githubusercontent.com/107079404/172484011-0cbb0294-f535-4c0f-b609-7601974c191a.png)

Exilence next v1.1.8

**Comment by viktorgullmark** [comment]
Try reinstalling to see if it resolves the issue, reopen if it doesnt.
