### ISSUE TITLE
Blurry UI all the time.

### ISSUE THREAD

**Issue by Brackz777** [viktorgullmark/exilence-next#834]
**Describe the bug**
The UI is always blurry no matter what I try - when I mouse over stuff it sometimes becomes clear until I mouse off of it.

**To Reproduce**
1. Open app
2. Hover mouse over different elements of UI
3. Goes blurry.

**Expected behavior**
I expected for it not to be blurry.

**Screenshots**
![image](https://user-images.githubusercontent.com/25531443/173401519-e6198378-92cf-4e24-83d2-7cec921122ed.png)

**Version**
1.1.8

**Additional context**

**Comment by sbsrnt** [comment]
1. Try disabling Hardware Acceleration in settings
2. Update your GPU drivers
