### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by MrDemonMike** [viktorgullmark/exilence-next#836]
**Describe the bug**
The app doesnt track item inventory and worn gear

**To Reproduce**
made a profile with only tracking of inventory and worn gear.
then take snapshot.
gave an error that it cannot track and if i put in the profile 1 stash tab and inventory and gear it only tracks that 1 stashtab

**Expected behavior**
tracking the worth of my inventory and gear

**Version**
exilence next v.1.1.8

**Comment by viktorgullmark** [comment]
What gear/item specifically? I suspect this is due to your item not being listed on poe.ninja. We only price whats on there.
