### ISSUE TITLE
404 failed to retrieve prices

### ISSUE THREAD

**Issue by Shimanim** [viktorgullmark/exilence-next#852]
I've been getting this error for about 4 hours now and I thought it might have just been me, but 2 people on global chat in PoE were reporting the same problem. I reset data and still no prices retrieved. Re-installed, restarted PC, still nothing.
Take snapshot button is completely greyed out and I can't use the program at all.

**Comment by sbsrnt** [comment]
Fixed in https://github.com/viktorgullmark/exilence-next/releases/tag/v1.2.1
