### ISSUE TITLE
Cannon Connect to POE Account

### ISSUE THREAD

**Issue by ddduncan3** [viktorgullmark/exilence-next#887]
Hello I have Exilence Next v1.2.1 The other day I was using the app but yesterday I tried to open it and it took me to the Login. I attempt to log in the Pathofexile.com, I then attempt to sign in through Steam and the window spins and gives me cannot locate site error. I reinstalled and it gives me the same error. I don't now how to fix it. Identifies my POE account in the sign in page.

My email is ddduncan3@comcast.net. Your help would be appreciated.

**Comment by liewentjan** [comment]
Same issue, redirection to "next.exilence.app/api/authentication/..." from POE sire fails not connect.

**Comment by Olenjan** [comment]
Same issue, redirection to "next.exilence.app/api/authentication/..." from POE site fails not connect.

**Comment by ddduncan3** [comment]
iM GETTING THIS Hmmm… can't reach this pagenext.exilence.app refused to connect.

**Comment by thbemme** [comment]
See https://github.com/viktorgullmark/exilence-next/issues/886#issuecomment-1715261503

**Comment by sbsrnt** [comment]
Exilence Next is no longer maintained.
