### ISSUE TITLE
Cannot connect app to my profile on PathofExile

### ISSUE THREAD

**Issue by satechheads** [viktorgullmark/exilence-next#889]
Secure Connection Failed

An error occurred during a connection to next.exilence.app. PR_END_OF_FILE_ERROR

Error code: PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

I installed the executable and ran it.
It asks me for an authorization to connect to my profile in browser.
I click the button to authorize the connection and I get the "secure connection failed" error.

**Version**
1.2.1.

I have not had any issues with other tools connecting to my account. I have it set to public.

**Comment by sbsrnt** [comment]
Exilence Next is no longer maintained.
